### ISSUE TITLE
Navbar on mobile covers part of cross-referenced content

### ISSUE THREAD

**Issue by McSinyx** [pradyunsg/furo#10]
### Describe the bug
Cross-referenced content like sections and terms are hidden under the navbar in mobile view.

### To Reproduce

0. Open a browser on mobile or resize it similarly
1. Go to https://urllib3.readthedocs.io/en/latest/user-guide.html#response-content

### Expected behavior
The page should be scrolled down a little to 

### Screenshots
Non-essential since the problem was perfectly described in words, however I want to flex my new phone a little:
![20200923_16h24m36s_grim](https://user-images.githubusercontent.com/13689192/93993877-77dd7280-fdb9-11ea-81ee-34098382b306.png)

### Desktop
- OS: Debian GNU/Linux testing
- Browser: Firefox ESR 68 and Chromium 83

### Smartphone
- Device: Pinephone 1.2a
- OS: Mobian
- Browser: Firefox ESR 68 and Epiphany 3.36.3

### Additional context
It looks alright on wide screens, so IIUC using fixed navbar instead of sticky would fixes the issue.

**Comment by pradyunsg** [comment]
Thanks for the issue! That was something I forgot to add the CSS for. :)

**Comment by McSinyx** [comment]
Thanks, that was quick!

**Comment by McSinyx** [comment]
BTW it'd be great if you can release another beta in the near future with fixes for this and GH-9!
