### ISSUE TITLE
kbd looks odd for key combinations

### ISSUE THREAD

**Issue by jackbentley** [pradyunsg/furo#102]
**Describe the bug**
The display of key combinations using kbd look odd in the theme.

**To Reproduce**
```rst
:kbd:`⌘+⇧+M`
```

**Expected behavior**
The output probably shouldn't be double bordered. Something similar to this:
<img width="103" alt="Screenshot 2021-03-16 at 12 10 17" src="https://user-images.githubusercontent.com/9383439/111306916-b78e6400-8650-11eb-9bc8-c4c44f252d81.png">

**Actual behavior**
<img width="86" alt="Screenshot 2021-03-16 at 12 10 33" src="https://user-images.githubusercontent.com/9383439/111306888-af362900-8650-11eb-86ac-0882933e35f5.png">

**Additional context**
Note the font size is also quite small. Both screenshots taken on the same computer with the same resolution and text size, etc.

**Comment by pradyunsg** [comment]
Huh. IDK why, but Sphinx converts that to:

```
<kbd><kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>M</kbd></kbd>
```

I would've expected:

```
<kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>M</kbd>
```

<kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>M</kbd> is what GitHub does for what I'd expected.

<kbd><kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>M</kbd></kbd> is what GitHub does for the HTML generated by Sphinx.

---

TBH, I have no idea why Sphinx does what this does. I'd suggest filing an issue upstream. :)

**Comment by dgw** [comment]
Probably related: sphinx-doc/sphinx#7530, sphinx-doc/sphinx#8619

**Comment by pradyunsg** [comment]
Bah, this seems like a mess.

**Comment by pradyunsg** [comment]
I can't seem to reproduce this either: see https://pradyunsg.me/furo/kitchen-sink/demo/, which contains 8671e1624a10e15990595d2ff65c2661890e9ef8

**Comment by jackbentley** [comment]
According to the linked Sphinx issues, it looks like the nesting is intentional and it adds the `compound` class for style targeting?

If it helps in reproducing, I have the following versions installed:
```
docutils                      0.16
furo                          2021.2.28b28
Sphinx                        3.5.1
sphinx-autobuild              2020.9.1
sphinx-multiversion           0.2.4
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
```

**Comment by pradyunsg** [comment]
https://github.com/pradyunsg/furo/commit/56b770220171494d3dbf2546afd111186584d4e8 did the stylesheet changes, FWIW.

**Comment by pradyunsg** [comment]
Released in beta29. :)
