### ISSUE TITLE
Align center on figure does not respect width setting

### ISSUE THREAD

**Issue by Luthaf** [pradyunsg/furo#103]
**Describe the bug**

I have the following rst (I can create a standalone example if that helps):

```rst
.. figure:: some-image.svg
    :width: 400px
    :align: center

```

I would expect that the resulting HTML renders the images centred in the main column, but with the requested width. Instead, the image takes half of the main column width (352px in my case), regardless of the requested width.

**Desktop (please complete the following information):**

- OS: macOS 14.6
- Browser: Chrome & Firefox & Safari all render the same

**Comment by pradyunsg** [comment]
Thanks for reporting this!

A standalone example would be super helpful!

**Comment by Luthaf** [comment]
Here is a standalone reproduction of this bug: 
[furo-bug.zip](https://github.com/pradyunsg/furo/files/6165027/furo-bug.zip)

Using furo, the image is quite small:

<img width="1439" alt="furo" src="https://user-images.githubusercontent.com/6141587/111647815-15fb4400-8803-11eb-8fea-78f73b3d144e.png">

While using alabaster, it takes the full width:

<img width="1440" alt="alabaster" src="https://user-images.githubusercontent.com/6141587/111647828-185d9e00-8803-11eb-9cd9-0ecb92c3f7ec.png">

**Comment by pradyunsg** [comment]
Okay, I love this reproducer. You definitely made my day a lot better with this. ^>^

**Comment by pradyunsg** [comment]
1ff0ae277d3a337ac4b28b9995dcc16827403d96 should fix this! I'll cut a release over the weekend. :)

**Comment by Luthaf** [comment]
thanks a lot!
