### ISSUE TITLE
Multi Column Layout

### ISSUE THREAD

**Issue by christopherpickering** [pradyunsg/furo#105]
Thanks for the great layout! Would it be possible to add in an option for column layout?

Pulling some syntax from https://stackoverflow.com/questions/56749718/how-to-make-2-columns-with-sphinx:

```rst
.. columns:: twocol

    .. column::

        text on left column

    .. column::

        text on right column
```

With a fluid layout, maybe similar to (Bluma)[https://bulma.io/documentation/columns/basics/]?

Sometimes documentation pages seem to drag on an on when the material could be placed side-by-side in column.

**Comment by pradyunsg** [comment]
Nothing that the theme provides natively.

I do highly recommend https://sphinx-panels.readthedocs.io/en/latest/ though, which gives you this and a lot more! :)

**Comment by christopherpickering** [comment]
Very cool, thanks!
