### ISSUE TITLE
Ideas for how to do external links

### ISSUE THREAD

**Issue by christopherpickering** [pradyunsg/furo#106]
It would be nice to have the option to open some links in a new tab, especially links to external sites.

There are a couple recommendations in this post - https://stackoverflow.com/questions/25583581/add-open-in-new-tab-links-in-sphinx-restructuredtext

But they both break the theme, the first recommendation breaks the TOC, and the second breaks table layout.

I wonder if we can do something like

```rst
.. link_ext:: www.google.com
```

or (this is bad idea but can't think of anything better on the spot lol)
```rst
`google <www.google.com>ext`_
```

What do you think? The other painful rst vs markdown .. no checklists? I know you will recommend me to use md 😀

**Comment by pradyunsg** [comment]
Oooo. This is an interesting idea, but likely belongs as a separate Sphinx extension TBH. I don't know of a good way to do this either TBH. :)

The #sphinx channel on https://writethedocs.slack.com/ might have better ideas than I do about this! :)

**Comment by pradyunsg** [comment]
Aaaand... filed the above issue for your checklist question. :)

**Comment by christopherpickering** [comment]
nice, thanks! It looks like it has to be done with myst, instead of plain rst?

**Comment by pradyunsg** [comment]
Well, not yet. Enabling that is what that issue is for! :)

**Comment by christopherpickering** [comment]
Cool! when I try w/ myst enabled in a rst doc:

```rst
- [ ] undone
- [x] done

```

![image](https://user-images.githubusercontent.com/17788706/111696956-f19f6780-8802-11eb-9341-a734a899ae77.png)

**Comment by pradyunsg** [comment]
Closing since this isn't specific to the theme, but more about what the markup languages support. It'd be better to take this up with those projects. :)
