### ISSUE TITLE
Method signature can overlap on the `[source]` link 

### ISSUE THREAD

**Issue by jack1142** [pradyunsg/furo#108]
**Describe the bug**
In some cases, the method signature can overlap on the `[source]` link.

Here's a preview:
https://jack1142-minimal-repro.readthedocs.io/en/latest/
And a bit different one (with usage of `sphinxcontrib_trio` extension):
https://jack1142-red-prs.readthedocs.io/en/v3-some_furo_stuff/framework_commands.html#redbot.core.commands.help.RedHelpFormatter.help_filter_func

**To Reproduce**
The code of minimal repro is here:
https://github.com/jack1142/furo/tree/issue_108_minimal_repro

**Expected behavior**
I expected the method signature to wrap appropriately.

**Screenshots**
![image](https://user-images.githubusercontent.com/6032823/111876160-c8ffa500-899d-11eb-91bf-ed423a41b687.png)
![image](https://user-images.githubusercontent.com/6032823/111875486-56d99100-899a-11eb-881b-072a3ffe7d69.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome 89, Opera 74, Firefox 86, Edge 89
- Screen Width: over 830px (I have 1080p screen)

**Smartphone (please complete the following information):**

Doesn't happen on my smartphone (Galaxy S20, Android 11, Chrome 89), although it does seem that some contents don't get wrapped causing horizontal scrolling to be required.

**Additional context**

**Comment by pradyunsg** [comment]
![Screenshot 2021-03-20 at 4 39 06 PM](https://user-images.githubusercontent.com/3275593/111877333-cd768e80-899a-11eb-8d9e-cdec6af44cc3.png)

Can't reproduce this on my end, on a 1080p screen, full-screen window. :/

**Comment by jack1142** [comment]
@pradyunsg that looks like you have `sphinxcontrib_trio` extension installed and enabled. I had that pushed in one of previous builds I generated but I changed it later to not include this. Only the second example was built with that extension installed and enabled.

**Comment by pradyunsg** [comment]
Well, I just visited https://jack1142-red-prs.readthedocs.io/en/v3-some_furo_stuff/framework_commands.html#redbot.core.commands.help.RedHelpFormatter.help_filter_func

None the less, I think I know what's happening; and this needs fun hacks to work around the issue here. :(

**Comment by pradyunsg** [comment]
Fixed in bb46d32aa4a977a0c825ec14b82fbfd04be4f0a4, I think. :)

**Comment by jack1142** [comment]
I've run a build on the latest commit and it seems to work fine on the second example:
https://jack1142-red-prs.readthedocs.io/en/v3-some_furo_stuff/framework_commands.html#redbot.core.commands.help.RedHelpFormatter.help_filter_func
![image](https://user-images.githubusercontent.com/6032823/111911254-172bab80-8a65-11eb-9bf3-d5f274c7a358.png)

However, the repro at https://jack1142-minimal-repro.readthedocs.io/en/latest/ still doesn't seem to wrap for me:
![image](https://user-images.githubusercontent.com/6032823/111911319-5b1eb080-8a65-11eb-85ce-bcdda45f465c.png)

**Comment by pradyunsg** [comment]
Ah, fun. Return type annotations.

PS: Dear past me, why did you close this without making a release or waiting for a response? 🙃

**Comment by pradyunsg** [comment]
1574348b19a857910ebb72947c2c3ed43301dd0d should help. Feel free to close this if this works! I'mma make a release sometime this weekend. :)

**Comment by jack1142** [comment]
Appears to be working fine now, awesome!
![image](https://user-images.githubusercontent.com/6032823/112679294-4a5aaa00-8e6c-11eb-82da-ce3e7f0f9994.png)

**Comment by pradyunsg** [comment]
Awesome!
