### ISSUE TITLE
Spacing issues in API docs

### ISSUE THREAD

**Issue by hynek** [pradyunsg/furo#11]
**Describe the bug**

Longer API (autodoc) documentation looks squeezed.

**To Reproduce**

Use something like `.. automethod` with a params that are multiple paragraphs, possibly contain ordered or unordered lists.

**Expected behavior**

It would be great to get some spacing.

**Screenshots**

<img width="750" alt="Screenshot 2020-09-28 at 12 04 29@2x" src="https://user-images.githubusercontent.com/41240/94424848-cb1d3f80-0182-11eb-91c0-4390d22c7334.png">

It looks especially unfortunate when having multiple short paragraphs:

<img width="721" alt="Screenshot 2020-09-28 at 12 05 24@2x" src="https://user-images.githubusercontent.com/41240/94424920-ec7e2b80-0182-11eb-971d-52f8ca6a2745.png">

Lists also look unhappy without any social distancing:

<img width="762" alt="Screenshot 2020-09-28 at 12 05 52@2x" src="https://user-images.githubusercontent.com/41240/94424946-facc4780-0182-11eb-8d7f-87adb469b479.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser Safari
- Version 14

---

Otherwise great work!

**Comment by sethmlarson** [comment]
You know your feature requests are new when they contain the phrase "social distancing" :) I'm ++ on this!

**Comment by pradyunsg** [comment]
I swear I remember fixing this a while back!

*(notices commits since last release)* Nvm, I just cut a release that should contain a fix for this. Let me know if that works and feel free to close this issue if it does. ^>^

<img width="742" alt="Screenshot 2020-09-28 at 9 58 35 PM" src="https://user-images.githubusercontent.com/3275593/94460071-d3eb3100-01d5-11eb-8577-b69d0e2a1e1c.png">

**Comment by hynek** [comment]
Hm, I\ve updated furo:

```
❯ pip list | grep furo
furo                          2020.9.28b8
```

And did a `make clean` and `make html`.

But it looks almost the same:

<img width="769" alt="Screenshot 2020-09-28 at 19 18 27@2x" src="https://user-images.githubusercontent.com/41240/94470308-68966480-01bf-11eb-9e83-119ab0816cd0.png">

<img width="781" alt="Screenshot 2020-09-28 at 19 18 51@2x" src="https://user-images.githubusercontent.com/41240/94470353-7ba93480-01bf-11eb-9bfe-38c755eddfbd.png">


I've even tried Firefox to make sure it's no weird caching stuff.

If it looked like in your screenshot, I'd be happy! Is it because my paragraphs are part of params?

**Comment by pradyunsg** [comment]
> Is it because my paragraphs are part of params?

Yes! That's a really nice catch. I'll get the attrs docs locally and iterate on this.

**Comment by hynek** [comment]
Splendid! Play your cards well, and I’ll be blaming you for broken attrs doc layouts in the future!

**Comment by pradyunsg** [comment]
Should be better with 606666351440cdcacf9d1d47d534f41b5a0da4ca! :)

**Comment by pradyunsg** [comment]
New beta release out, containing said fixes.

**Comment by hynek** [comment]
It is! I have two minor quibbles, lmk if you want me to open issues for that:

- the terms in the glossary aren't styled: https://www.attrs.org/en/latest/glossary.html (bold would be great?)
- on macOS Safari, the hover in the left side-bar looks broken (it doesn't happen in FF/Edge) 
![Screenshot 2020-10-05 at 06 45 56](https://user-images.githubusercontent.com/41240/95044077-71fb6180-06d6-11eb-8457-501785e46de4.png)

**Comment by pradyunsg** [comment]
> the terms in the glossary aren't styled:

Yup. 

> on macOS Safari, the hover in the left side-bar looks broken

Aaargh. SAFARI is why we can't have good things. :)

**Comment by pradyunsg** [comment]
Separate issues would be great, because I get
the happy feeling of closing issues by actually fixing them. :)

**Comment by hynek** [comment]
OK, but no templates for you! ;)

**Comment by hynek** [comment]
Filed as #15 and #16. **This** issue is done now, thank you very much!
