### ISSUE TITLE
Add styling for non-panel parts of sphinx-panels

### ISSUE THREAD

**Issue by RobertCraigie** [pradyunsg/furo#111]
**Describe the bug**
sphinx-panels dropdown directive does not respect dark mode if it is not within a panels directive

**To Reproduce**
sorry I don't have a full repro, but here's the page I used to test this

```rst
Bug
===

.. panels::

    Content of the top-left panel

    ---

    Content of the top-right panel

    :badge:`example,badge-primary`

    ---

    .. dropdown:: :fa:`eye,mr-1` Bottom-left panel

        Hidden content

    ---

    .. link-button:: https://example.com
        :text: Clickable Panel
        :classes: stretched-link


.. dropdown:: Click on me to see my content!

    I'm the content which can be anything:

    .. link-button:: https://example.com
        :text: Like a Button
        :classes: btn-primary

```

**Expected behaviour**
The dropdown at the bottom of the page should also have a dark background

**Screenshots**
https://gyazo.com/b53f60444de0427d08b270a280f9784e
https://gyazo.com/2ed3766faa9d43325e8b020311ad78a6

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.2.1
- Browser: safari
- Version: 14.0.3

**Additional context**
Using the latest PyPi version for both Furo and sphinx-panels

**Comment by pradyunsg** [comment]
GAH. Bootstrap colors. >.<

What's happening here is that custom colors are being set for sphinx-panel's panels, but not for the dropdowns (which are inheriting them from sphinx-panels) -- see https://github.com/pradyunsg/furo/blob/main/src/furo/assets/styles/extensions/_sphinx-panels.sass.

I guess the fix would be to add styling more for sphinx-panels things... Oh boy. That's gonna be a fun one.

**Comment by chrisjsewell** [comment]
Note sphinx-panels will eventually be deprecated for the new shiny https://sphinx-design.readthedocs.io/en/furo-theme 😄

**Comment by chrisjsewell** [comment]
So there this is basically the minimal css I've happened to work with dark mode: https://github.com/executablebooks/sphinx-design/blob/6b5982110bd4fb8a6d7ff6ec3ba16bb819ec39b6/docs/_static/sd-furo.css#L1

**Comment by ScriptAutomate** [comment]
> Note sphinx-panels will eventually be deprecated for the new shiny https://sphinx-design.readthedocs.io/en/furo-theme smile
> 
> the colors here are all css variables, so hopefully should be easier to override: https://sphinx-design.readthedocs.io/en/furo-theme/css_variables.html

@chrisjsewell Awesome! Just wanted to say thanks for pointing this out, because that's exactly the kind of stuff I've been looking for to resolve some of our docs layouts in my projects.

**Comment by pradyunsg** [comment]
Added direct support for sphinx-design in db4dd7395d7f962a1fd02e90eb3e182ca316d518.

I'm gonna say that is enough, and we can close this now.

**Comment by pradyunsg** [comment]
Oh, and once released, this is how sphinx-design stuff will look in Furo: https://pradyunsg.me/furo/kitchen-sink/sphinx-design/

**Comment by chrisjsewell** [comment]
I note the commit doesn’t seem to change the colours when in dark mode, like the current furo css does in sphinx-design?

**Comment by pradyunsg** [comment]
It does. All the variables used there are modified when the page is in dark mode.

**Comment by pradyunsg** [comment]
Further, what's there in the sample doc for sphinx-design right now won't work with Furo versions that have the dark mode toggle.

**Comment by chrisjsewell** [comment]
Maybe I'm missing something in the implementation, but what if you used e.g. `:color: dark`? In https://github.com/executablebooks/sphinx-design/blob/68b75e8cda9b3760555e6aaca3739ca3266fd8e9/docs/_static/sd-furo.css#L1 it changes `--sd-color-light` and `--sd-color-dark` when in dark mode, but I don't see that here?

**Comment by pradyunsg** [comment]
> `:color: dark` for a button?

It'll be dark, regardless of dark mode vs light mode? I don't think "dark" should look light on dark mode or vice-versa. 🤷🏽

**Comment by chrisjsewell** [comment]
> I don't think "dark" should look light on dark mode or vice-versa. 🤷🏽

yeh hmm, maybe the naming of `light` and `dark` should be changed to something like `high-contrast` and `low-contrast`, since this is how I envisage them being used semantically. What do you think?

**Comment by pradyunsg** [comment]
I can't imagine any good reason to have `low-contrast` content. 🤷🏽 

Let's move the discussion to https://github.com/executablebooks/sphinx-design/pull/22?

**Comment by pradyunsg** [comment]
Released in beta43.
