### ISSUE TITLE
Support for Sphinx's `html_show_*` configuration variables

### ISSUE THREAD

**Issue by McSinyx** [pradyunsg/furo#12]
### Describe the bug
[html_show_sourcelink, html_show_copyright and html_show_sphinx](https://www.sphinx-doc.org/en/master/usage/configuration.html) are currently ignored by furo.

### To Reproduce
In conf.py add the following

```python
html_show_sourcelink = True
html_show_copyright = False
html_show_sphinx = False
```

Rebuild the docs and observe that copyright and sphinx are shown but source link is nowhere to be found.

### Expected behavior
Sphinx configuration should be respected.  ~Furthermore, it'd be really nice if the version of Sphinx as well as Furo is displayed (if html_show_sphinx is True) for debugging.~

### Platform
Irrelevant, I think.

**Comment by pradyunsg** [comment]
The versions are available in the `<head>`, as a meta tag for the generator.

**Comment by pradyunsg** [comment]
This is done now, released in beta15.

**Comment by McSinyx** [comment]
Thanks!
