### ISSUE TITLE
Glossary items are unstyled

### ISSUE THREAD

**Issue by hynek** [pradyunsg/furo#15]
It would be nice if glossary items like in https://www.attrs.org/en/latest/glossary.html could by styled. E.g. bold would be great:

![Screenshot 2020-10-05 at 10 35 07](https://user-images.githubusercontent.com/41240/95063602-746db380-06f6-11eb-89ed-835ba29a093d.png)

**Comment by pradyunsg** [comment]
Fixed in 5caf736fcde24257460e652a4117f9057a80bbf2. :)
