### ISSUE TITLE
Sphinx 4: Custom CSS injection does not work

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/furo#168]
### What's happening?

Custom CSS set in the configuration file, is not affecting the page, on Sphinx 4.

### Reproducer

Discussed in https://github.com/pradyunsg/furo/discussions/162

- Build a documentation set, with Furo's custom CSS overrides (per https://pradyunsg.me/furo/customisation/colors/#defining-overrides-for-defaults for example)
- Notice that the overrides are not in effect.

### Expectation

Looks like Sphinx 4's stylesheet changes, affected more than just pygments stuff (noticed in  e49e5dde09a71998dc334929921083e8b071fc6c).

**Comment by lalmeras** [comment]
As I understand the issue, it is related to the fact that Sphinx 4.x adds theme stylesheet in `css_files`.

It seems that applying an exclusion in `base.html` like it is already done for `pygments_dark` is a way to fix this without breaking Sphinx 3 ?

I try this fix (crappy way to write the string condition in a way that ignores digest=... fragment) and it seems to work as expected. `furo.css` is not added after the inlined style tag.

```jinja2
    {%- for path in css_files -%}
    {% if not path.filename.startswith("pygments_dark") and not pathto(furo_assets['style'], 1).startswith(path.filename) -%}
      {{ css_tag(path) }}
    {%- endif %}
```

**Comment by pradyunsg** [comment]
Yea, basically. From the Sphinx changelog:

> * html theme: Move a script tag for documentation_options.js in
>  basic/layout.html to ``script_files`` variable
> * html theme: Move CSS tags in basic/layout.html to ``css_files`` variable

I, somehow, completely missed this.

**Comment by pradyunsg** [comment]
This should be fixed by d3a43e630dcdcf67540270518e4354d3ebe707e6, taking a more nuclear option of dropping the digests and leaning into Sphinx's default behaviour.

![Screenshot 2021-06-24 at 9 25 55 PM](https://user-images.githubusercontent.com/3275593/123327733-a3e97800-d532-11eb-980c-f90f9f85f81f.png)

**Comment by pradyunsg** [comment]
Released in beta37.

**Comment by mdurrani808** [comment]
Is this confirmed to be fixed? I'm still seeing this locally. I can link code if needed.

**Comment by pradyunsg** [comment]
Yes. Please open a discussion topic for this.

**Comment by adamgayoso** [comment]
Don't have a minimal example yet, but this reproduces with Sphinx 4.4. Version 4.3 works as expected.
