### ISSUE TITLE
Android: Version selector floating too high

### ISSUE THREAD

**Issue by hugovk** [pradyunsg/furo#17]
**Describe the bug**

The docs version selector floats a bit too high up. 

**To Reproduce**

1. Go to https://www.attrs.org/en/stable/ on Chrome on Android (Samsung S8) 
2. Check the location of the version selector 

**Expected behavior**

The selector is perhaps flush with the bottom of the screen, or in the left menu. 

**Screenshots**

![Screenshot_20201005-124006_Chrome](https://user-images.githubusercontent.com/1324225/95064450-69bc1a00-0708-11eb-9765-2ff16a7ad6fd.jpg)

![Screenshot_20201005-123956_Chrome](https://user-images.githubusercontent.com/1324225/95064455-6aed4700-0708-11eb-97eb-fa8803c7f963.jpg)

**Smartphone (please complete the following information):**

- Device: Samsung S8
- OS: Android
- Browser: Chrome
- Version: 85

**Comment by pradyunsg** [comment]
Hmm... The other option is that it overlaps with the navigation at bottom of the page. :(

**Comment by hugovk** [comment]
sphinx_rtd_theme puts it in the left menu. 

https://pillow.readthedocs.io/en/stable/

![Screenshot_20201005-124700_Chrome](https://user-images.githubusercontent.com/1324225/95064936-0ed6f280-0709-11eb-8bf3-3152c937a309.jpg)

**Comment by pradyunsg** [comment]
> sphinx_rtd_theme puts it in the left menu.

I was checking the RTD documentation earlier for how to add both the ad as well as the docs navigation there. There's barebones documentation for the ad, but nothing for the navigation embed that they have.

**Comment by hugovk** [comment]
Hmm, I reloaded and it's now in the same place as sphinx_rtd_theme, in the left menu. No code changes or RTD rebuilds, or cache clearings. Maybe it was a one off!

**Comment by pradyunsg** [comment]
FWIW, this is higher due to the specific CSS I've added for this -- https://github.com/pradyunsg/furo/commit/1aac39f641fccf94c8e3387460122176780e1a29. This area is up for discussion, around how we'd change this to work best.

Right now, I've prioritized making the bottom of page navigation more visible (on desktop) since I think navigation gets a bit more priority than the content in this case. I'm all ears for other opinions though. :)

**Comment by hynek** [comment]
FWIW, it doesn't just float too high, it's also very broken on Safari & FF, if you try to open it:

![Screenshot 2020-10-05 at 11 03 47](https://user-images.githubusercontent.com/41240/95066570-7afe2a00-06fa-11eb-8398-e0764faad013.png)

Edge suggest it's a z-index issue:

![Screenshot 2020-10-05 at 11 05 30](https://user-images.githubusercontent.com/41240/95066788-c57fa680-06fa-11eb-9b1f-fc32a927cfd0.png)

Not sure if new issue or belongs here?

**Comment by pradyunsg** [comment]
ARGH. z-indexes are horrible and break everything. Fixed that issue in ac09927fddd29313b97a4f6a06448285cbac1fcf. :)

**Comment by pradyunsg** [comment]
I've gone ahead and dropped this in ac251fd. I'll revisit this properly at a later date though.

Closing this for now, since it's "fine" without this override.
