### ISSUE TITLE
Infinite scroll on firefox

### ISSUE THREAD

**Issue by johnnoone** [pradyunsg/furo#19]
**Describe the bug**
On firefox, when starting scrolling a page with a massive number of TOC entries (40 in my case), the page does not stop to scroll to the end of the page.

**To Reproduce**
1. Create a page with at least 40 entries in TOC (TOC height must be greater than window height)
2. Start to scroll down the page on firefox
3. Javascript keeps scrolling to the end of the page

**Expected behavior**
Should behave like on safari

**Desktop (please complete the following information):**

- OS: Catalina
- Browser firefox
- Version 81.0.1

**Comment by pradyunsg** [comment]
Hi! Thanks for filing this issue!

I'm a FF-on-MacOS user myself, and am unable to reproduce this locally.

By any chance, could you take a short video/gif of this behaviour and share that?

**Comment by pradyunsg** [comment]
AHHHH! Okay, now I see what you mean. Interesting!

**Comment by McSinyx** [comment]
> AHHHH! Okay, now I see what you mean. Interesting!

[What did you see?](https://xkcd.com/979/)

**Comment by pradyunsg** [comment]
a83b9021134ce9adb48b205022011d393be54aae should resolve this for now. I'd need to make a bunch of tiny changes to get the right sidebar auto-scroll working just right, which I'll get to later.
