### ISSUE TITLE
Remove underline from ¶ links

### ISSUE THREAD

**Issue by hugovk** [pradyunsg/furo#20]
**Describe the bug**

Remove underline from ¶ links.

**To Reproduce**

1. Go to https://pradyunsg.me/furo/quickstart/
2. Hover over "Quickstart" or ¶

**Expected behavior**

There's usually no underline under the ¶ character.

**Screenshots**

![image](https://user-images.githubusercontent.com/1324225/96089748-f2d50d00-0ecf-11eb-976b-91f1018fd628.png)

![image](https://user-images.githubusercontent.com/1324225/96090000-48a9b500-0ed0-11eb-8885-bb041ab88b74.png)

![image](https://user-images.githubusercontent.com/1324225/96090028-53644a00-0ed0-11eb-874a-3ba662bd6af8.png)

![image](https://user-images.githubusercontent.com/1324225/96090051-5828fe00-0ed0-11eb-961d-a47f1addda68.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 86

**Additional context**

Happens for both light and dark modes.

**Comment by pradyunsg** [comment]
Hmmm... I noticed it too, but I'm wondering what might be the best way to deal with this.

Would folks ever care about knowing the hover state here? If not, then this sounds like the best option.

**Comment by hugovk** [comment]
`text-decoration: none;` should be enough, that's what https://docs.python.org/3/whatsnew/3.9.html#what-s-new-in-python-3-9 has.

They also have the foreground/background colour change, I don't have a strong opinion on that.

I think the main thing is to remove the underline, and let the cursor pointer change as usual.

**Comment by pradyunsg** [comment]
Done in eaeadc0.
