### ISSUE TITLE
RTD: Ad shown at bottom of page instead of in left menu

### ISSUE THREAD

**Issue by hugovk** [pradyunsg/furo#23]
**Describe the bug**

I ran into the issue I mentioned at https://github.com/python-pillow/Pillow/pull/4968#issuecomment-708941627:

On mobile with the advert shows at the bottom of the page rather than hidden in the left menu.

**To Reproduce**

1. Go to https://pillow-hugovk.readthedocs.io/en/furo/ on mobile
2. Hope you get served ads this time
3. The advert is placed at the bottom of the screen

**Expected behavior**

The ad is tucked away in the side menu like with sphinx_rtd_theme

**Screenshots**

<img width=48% src=https://user-images.githubusercontent.com/1324225/96223631-e7004e00-0f96-11eb-9648-7d8b28c4b8bc.jpg> <img width=48% src=https://user-images.githubusercontent.com/1324225/96223644-e9fb3e80-0f96-11eb-9eb2-5d572ba02c23.jpg>

**Smartphone (please complete the following information):**

- Device: Samsung S10
- OS: Android
- Browser Chrome
- Version 86

**Additional context**

This is also the HTML downloaded from Chrome on the phone. Looks like it gets monkeyed with a bit by Chrome's HTML downloader, but hopefully you can still see the important structure.

[Home - Pillow (PIL Fork) 8.1.0.dev0 documentation.html.zip](https://github.com/pradyunsg/furo/files/5389782/Home.-.Pillow.PIL.Fork.8.1.0.dev0.documentation.html.zip)

(I'm not getting ads now, will do a view source and grab that if it happens again.)

**Comment by pradyunsg** [comment]
ce1dfe417a9905636e262f7acb60bbe261d1445c should make things better.

**Comment by hugovk** [comment]
Looking good now with newest 2020.11.01.beta14 👍

![Screenshot_20201109-105110_Chrome](https://user-images.githubusercontent.com/1324225/98519694-cc5d8400-2279-11eb-86e6-45fe4b665e7d.jpg)

**Comment by pradyunsg** [comment]
There's an upstream request to get the colors right: https://github.com/readthedocs/ethical-ad-client/issues/37
