### ISSUE TITLE
Any way to get the RTD builds/versions box to show when used on RTD?

### ISSUE THREAD

**Issue by cjw296** [pradyunsg/furo#25]
**Is your feature request related to a problem? Please describe.**

The default RTD theme has a handy little pop-up bottom left that lets you pick the version of the docs to see, and also links to the project and builds on rtd.

**Describe the solution you'd like**

It would be great if that functionality could be surfaced in Furo, of course, I have no idea if or how it could be implemented.

**Comment by pradyunsg** [comment]
It works, if you have deployed on ReadTheDocs -- see https://sphinx-inline-tabs.readthedocs.io/en/latest/ for an example.

**Comment by cjw296** [comment]
Ah, so it does... any reason to move it bottom right? I think I was expecting it bottom left and I can't see a good reason for it not to be there?

**Comment by pradyunsg** [comment]
RTD's embedding JS works that way.

I could pretend to it that this theme is "RTD-theme-like" but it's much easier to let it do the default thing and embed it the way it does on themes that aren't Sphinx-RTD-Theme derivatives (see https://pip.pypa.io as an example of other themes having this behavior).

**Comment by cjw296** [comment]
Oh, right, yeah, I guess this becomes a feature request for RTD: https://github.com/readthedocs/readthedocs.org/issues/7589

**Comment by pradyunsg** [comment]
Coolieo. I don't mind it working as it does FWIW.
