### ISSUE TITLE
Use the list styling that Sphinx explicitly notes

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/furo#261]
### What's happening?

From #235:

> Furo misses to define a list-style for non-arabic lists. This makes nested list look very ugly, as they are all numbered with 1., 2.

### Reproducer

See https://pradyunsg.me/furo/kitchen-sink/lists_tables/#enumerated-lists vs https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/lists_tables.html#enumerated-lists.

### Expectation

The lists show up as Sphinx marks them.

There's a bit of CSS suggested for this in #235, by @latosha-maltba!

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/pradyunsg/furo/blob/main/CODE_OF_CONDUCT.md).

**Comment by michcio1234** [comment]
This is a critical issue for me which makes me go back to [RTD theme](https://github.com/readthedocs/sphinx_rtd_theme) (which is uglier than Furo). :(
