### ISSUE TITLE
Ability to select different logo in dark mode

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/furo#27]
**Is your feature request related to a problem? Please describe.**
Lack of contrast for logos when used for both dark and light more.

**Describe the solution you'd like**
Ability to select different logo in dark mode.

**Describe alternatives you've considered**
Telling users to adapt their SVG based on state (bad idea).

**Additional context**
@hynek flagged this on Twitter a little while back, and I can't find the tweet. :)

**Comment by hugovk** [comment]
> Random q from testing on mobile: is it possible to define a different logo for dark mode? If not, puhlease? Check attrs’s docs in dark mode for why. 😅

https://twitter.com/hynek/status/1316652913670979584


![image](https://user-images.githubusercontent.com/1324225/98519221-201b9d80-2279-11eb-8a1c-3cb237b9938d.png)

https://www.attrs.org/en/stable/

**Comment by pradyunsg** [comment]
This is done with 2d0a62792acfca161486aaed034b1ce2dac2de09.

**Comment by pradyunsg** [comment]
https://github.com/pradyunsg/furo/commit/3d89d56d5e7722fb450bdde2e1433f53ae1dd3d3 contains a critical fix to make this a reality.

Expect a release with it sometime later this week.

**Comment by pradyunsg** [comment]
This is out now, within the latest release. :)

**Comment by hynek** [comment]
Yayyy

![Screenshot 2020-11-16 at 07 55 00](https://user-images.githubusercontent.com/41240/99221622-3083c900-27e1-11eb-865f-020ad2e81bc5.png)
