### ISSUE TITLE
Top bar flickers while scrolling on mobile

### ISSUE THREAD

**Issue by hynek** [pradyunsg/furo#29]
A massive GIF says more than a thousand words:

![out](https://user-images.githubusercontent.com/41240/98702357-8dfbbe00-237a-11eb-9852-751203b9d437.gif)

**Comment by pradyunsg** [comment]
Ah, the joys of web development. 🌈 

Fixed in 978bc4f13d8ff60c6783a33096fe032fc21495b8.

**Comment by sethmlarson** [comment]
I wish all my bug reports were GIFs :pray:

**Comment by pradyunsg** [comment]
The fix is out now, within the latest release. :)
