### ISSUE TITLE
Double line when code statement is also a hyperlink

### ISSUE THREAD

**Issue by pavithraes** [pradyunsg/furo#3]
Example:
<img width="753" alt="Screenshot 2020-09-05 at 4 59 43 PM" src="https://user-images.githubusercontent.com/33131404/92304176-349d9a00-ef99-11ea-8643-1f55b515db12.png">

When a code statement is also a hyperlink, that underline (double line) is bothering me a little. 🙈

**Comment by pradyunsg** [comment]
I'm not sure what even this should look like if this is changed. Any specific thoughts on how else this could be stylized?

@sethmlarson Any opinions on this?

**Comment by sethmlarson** [comment]
Maybe removing the underline on code block links would be good? I think that's how Github styles things. 

[`example`](https://example.com)

**Comment by pradyunsg** [comment]
Nice! I'mma copy GitHub. :)

**Comment by pradyunsg** [comment]
Didn't remove the underline, but removed the border in 9a59e6e610a30a12d3d1548df13073b49d5c799e.

Looks like this now: <img width="198" alt="Screenshot 2020-09-08 at 5 33 19 PM" src="https://user-images.githubusercontent.com/3275593/92474406-644add00-f1f9-11ea-90ec-d46c97135419.png"> -- see https://pradyunsg.me/furo/demo/demo.html.

Feel free to close this if it looks good. If not, lemme know what you'd say needs tweaking. :)

**Comment by pavithraes** [comment]
@pradyunsg I like it! Thank you so much. :)
