### ISSUE TITLE
Insert custom stylesheets after theme stylesheets

### ISSUE THREAD

**Issue by bastimeyer** [pradyunsg/furo#30]
**Is your feature request related to a problem? Please describe.**
I've been trying to customize/extend furo via Sphinx's `html_css_files` directive, but [custom stylesheets do unfortunately get inserted into the document's `head` node first, before furo's own stylesheets](https://github.com/pradyunsg/furo/blob/3d89d56d5e7722fb450bdde2e1433f53ae1dd3d3/src/furo/theme/base.html#L50-L65). This makes it unnecessarily difficult to override certain styles, because the theme's default ones take precedence due to this stylesheet order. The only solution to this is setting `!important` flags on the properties, or defining stronger CSS selectors, or extending the `theme_styles` block in the `base.html` template and not using the `html_css_files` directive, which is all non-ideal and rather painful.

**Describe the solution you'd like**
It would be much easier to override the theme's CSS properties (or even CSS variables which are not defined via the theme options) if the custom CSS stylesheets were inserted after furo's own stylesheets.

**Comment by pradyunsg** [comment]
Hhmmmmmmm! Thanks for filing this!

I'm a little torn on this, since higher specificity is something I'm personally OK with. OTOH, Furo has styles for certain extensions that need to be set after the extensions themselves.

I guess it's OK to split the CSS into two on Furo's end, but ehhhh. Maybe... I should use specificity hacks on Furo's end.

**Comment by pradyunsg** [comment]
Done with 27dcc23f2b520b51b60ae694a1f5476988fd6825.

The overrides happen in a separate CSS file for now.

**Comment by pradyunsg** [comment]
This is out now, within the latest release. :)
