### ISSUE TITLE
Metadata for nicer previews when sharing

### ISSUE THREAD

**Issue by hynek** [pradyunsg/furo#31]
There's a bunch of metadata like OpenGraph or Twitter that allow for rich previews. I've just run into https://github.com/hynek/structlog/issues/197 and I guess it's time to pester _you_ with it. :)

To give you a starting point, my hopepage puts this in the `<header>`:

```html
    <meta property="og:site_name" content="Homepage and blog of Hynek Schlawack">
    <meta property="og:author" content="Hynek Schlawack">
    <meta property="og:type" content="article">
    <meta property="og:title" content="Waiting in asyncio">
    <meta property="og:description" content="One of the main appeals of using Python’s asyncio is being able to fire off many coroutines and run them concurrently. How many ways do you know for waiting for their results?">
    <meta property="og:url" content="https://hynek.me/articles/waiting-in-asyncio/">
    <meta property="article:published_time" content="2020-05-21T00:00:00Z">
    <meta name=twitter:card content="summary">
    <meta name=twitter:site content="@hynek">
    <meta name=twitter:creator content="@hynek">
    <meta name=twitter:image content="https://hynek.me/img/avatar.jpg">
    <meta name=twitter:title content="Waiting in asyncio">
    <meta name=twitter:description content="One of the main appeals of using Python’s asyncio is being able to fire off many coroutines and run them concurrently. How many ways do you know for waiting for their results?">
```

**Comment by pradyunsg** [comment]
Can't this be set using `.. meta`?

**Comment by pradyunsg** [comment]
Yea... Don't ask me why I remember this off the back of my head.

https://docutils.sourceforge.io/docs/ref/rst/directives.html#meta

Is this something I should describe in the customisation section?

**Comment by sethmlarson** [comment]
This would be super awesome, it'd make it a lot easier to check off this issue: https://github.com/urllib3/urllib3/issues/1983

**Comment by pradyunsg** [comment]
To quickly clarify what I meant above -- it is possible to achieve this today, since the handling of meta tags is done purely using what Sphinx provides, without support for any theme.

There's definitely a case for handing the title though (that's where the theme can actually do something to simplify the workflow, by autopopulating this); however, that's a quality of life thing (that Furo should do!) and the rest is basically common across all pages on the website. You can use `rst_epilog` for that.

For the example that @hynek gave above, the way to include that on *all* pages of a Sphinx site would be, to add the following in the `conf.py`:

```py
rst_epilog = """
.. meta::
    :property=og:site_name: Homepage and blog of Hynek Schlawack
    :property=og:author: Hynek Schlawack
    :property=og:type: article
    :property=og:title: Waiting in asyncio
    :property=og:description: One of the main appeals of using Python’s asyncio is being able to fire off many coroutines and run them concurrently. How many ways do you know for waiting for their results?
    :property=og:url: https://hynek.me/articles/waiting-in-asyncio/
    :property=article:published_time: 2020-05-21T00:00:00Z
    :twitter:card: summary
    :twitter:site: @hynek
    :twitter:creator: @hynek
    :twitter:image: https://hynek.me/img/avatar.jpg
    :twitter:title: Waiting in asyncio
    :twitter:description: One of the main appeals of using Python’s asyncio is being able to fire off many coroutines and run them concurrently. How many ways do you know for waiting for their results?
"""
```

Expect a documentation update, adding a page in https://pradyunsg.me/furo/customisation/ -- after pip 20.3 is out and the dust settles. :)

**Comment by hynek** [comment]
Looks like rst_epilog screws up includes:

```
/Users/hynek/FOSS/structlog/docs/changelog.rst:1: WARNING: Error in "include" directive:
no content permitted.

.. include:: ../CHANGELOG.rst

    :property=og:site_name: structlog – Structured Logging for Python
    :property=og:author: Hynek Schlawack
    :twitter:image: https://www.structlog.org/en/latest/_static/structlog_logo_small.png
    :twitter:creator: @hynek
    :twitter:image: https://www.structlog.org/en/latest/_static/structlog_logo_small.png
```

**Comment by pradyunsg** [comment]
Did you miss the `.. meta`?

I'd tried locally on attrs' docs, and it worked fine.

**Comment by hynek** [comment]
You're right, I've added some basic info now. I can't be bothered to add a separate title for each page tho. :-/

You should definitely document it tho. :)

Thanks!
