### ISSUE TITLE
Sidebar main menu scrollbar

### ISSUE THREAD

**Issue by bastimeyer** [pradyunsg/furo#32]
**Is your feature request related to a problem? Please describe.**
I've been trying to migrate the theme of our project's documentation to furo. This requires a customization of the theme's sidebar and adding a logo, title, oneliner/short-description and a version selection to the top of it, which means that the main menu moves down by a bit.

The issue I'm seeing with the theme's current main menu layout however is that on smaller screen heights, the sidebar's vertical scrollbar does only affect the main menu, not the entire sidebar. I don't think this is a good solution, because depending on the screen size and the height of the "sidebar header", the scrolling area of the main menu can become tiny and barely able to use (see first screenshot below).

I think that this should be changed/fixed in the theme, as it already optionally supports logos, which means that the available vertical space of the main menu is variable and not strict.

**Describe the solution you'd like**
The scrollbar should cover the entire sidebar.

However, the problem with a scrollbar on the sidebar is that when it appears (`overflow: auto`), it'll change the center alignment of the content, as the width shrinks. This needs to be taken into account.

Without changing any padding/margin properties of the sidebar layout, this worked for me while quickly testing the behavior in Chromium's dev tools, but it's just a hack and not a proper solution:
```css
.sidebar-sticky {
  overflow-y: overlay;
}
.sidebar-scroll {
  overflow: unset;
  flex-shrink: unset;
}
```

I don't know how well `overflow-y: overlay` is supported by current and last-gen browsers. caniuse.com doesn't list the property's value, as the property's behavior has been moved to `scrollbar-gutter` in the CSS overflow module level 4 spec, but Chromium 86 doesn't seem to support it yet AFAICT.

- https://caniuse.com/css-overflow
- https://www.w3.org/TR/css-overflow-4/#scollbar-gutter-property

**Describe alternatives you've considered**
See how it's done here for example:
https://docs.codecov.io/docs

**Additional context**
![image](https://user-images.githubusercontent.com/467294/99141900-06e76800-2650-11eb-838b-8c1c5dab130b.png)
![image](https://user-images.githubusercontent.com/467294/99141886-db647d80-264f-11eb-940d-e79017df1ffe.png)

Thank you!

**Comment by pradyunsg** [comment]
Yea, I need to tweak the sidebar customisation stuff a fair bit.

My rough plan is:

- add support for Sphinx’s html_sidebars 
- breakout the “scroll start” and “scroll end” snippets into dedicated templates that are order dependent and user configurable.

Does that sound A-OK?

**Comment by pradyunsg** [comment]
See https://github.com/pradyunsg/furo/commit/4f6d68a1d414136f0558ae94fabb9807c8c66d87 (or the corresponding page in the generated documentation).

**Comment by bastimeyer** [comment]
Sorry for the lack of response earlier, but this doesn't fix the whole issue.

While I appreciate your quick fix regarding the scrolling area, the sidebar's scrollbar unfortunately is still pushing the centered content to the left once it appears when changing the document height / window size. As said, this is something which can of course be fixed in the user's custom stylesheets if they already customize their sidebar, but I think that this is a theme issue which needs fixing here by applying a left and right padding to the sidebar's content, so that the scrollbar doesn't affect the available space once it appears.

Same issue with the TOC sidebar on the right. Once the scrollbar appears, the content becomes narrower which might cause long text rows to break into two (or more) lines. This is especially noticable and thus annoying here, since the `overflow:auto` property gets set on hover.

----

Btw, I think there's also an issue with the right sidebar and one of the media width queries, and the right sidebar doesn't disappear on the correct threshold, which causes horizontal scrollbars on the body to show up for a couple of pixels. I've also noticed an issue with the search input field and its icon, which floats around when the sidebar gets scrolled. I'm currently not on my computer while writing this though, and I've only noticed that earlier today, so I might be wrong here, as I can't verify my claims right now before posting it. Just wanted to mention it along my other comments. Will update this post with a verification once I got the time, or open a new issue then.

**Comment by pradyunsg** [comment]
> the sidebar's scrollbar unfortunately is still pushing the centered content to the left once it appears when changing the document height / window size.

Could you file an issue including reproduction info, screenshots and OS information? Your current description makes it unclear what exactly is "expected behaviour vs current behaviour".

> Will update this post with a verification once I got the time, or open a new issue then.

Please do file a new issue for this, if this is indeed still reproducible! :)
