### ISSUE TITLE
Rubrics have plaintext styling

### ISSUE THREAD

**Issue by hoefling** [pradyunsg/furo#33]
First of all, kudos for this awesome theme. Finally, a modern UI for Sphinx docs has arrived! :fireworks: 

**Is your feature request related to a problem? Please describe.**

I'm using the ``.. rubric::`` directive quite extensively. A simple example:

```rst
Initialize optimal bias weights.

.. rubric:: Standalone usage

>>> x = 0

.. rubric:: Usage in optimal model

>>> x = 1

.. rubric:: Usage in trainable model

>>> x = 2

.. rubric:: Formulae

Lorem ipsum dolor sit amet.
```

Using e.g. `alabaster` or `sphinx-rtd-theme`, they are rendered in bold:
<details>
  <summary>Image</summary>

  ![image](https://user-images.githubusercontent.com/4455652/99676161-71493f80-2a78-11eb-9ab0-cf352040e2cf.png)
</details>

With `furo`, the rubrics are rendered as plain text:

<details>
  <summary>Image</summary>

  ![image](https://user-images.githubusercontent.com/4455652/99676355-ac4b7300-2a78-11eb-8fbb-c74b16d9f685.png)
</details>

**Describe the solution you'd like**

I'm not sure actually what the best styling would be for the rubrics :shrug: The default CSS for the rubric class seems to be

```css
p.rubric {
    margin-top: 30px;
    font-weight: bold;
}
```

([relevant spot in `basic.css_t`](https://github.com/sphinx-doc/sphinx/blob/68c91b19208cff332eacf30908b63b80482fafb8/sphinx/themes/basic/static/basic.css_t#L275)), but maybe you can find a better one? I find e.g. the solution with centered captions very elegant, maybe something similar is suitable here also.

**Describe alternatives you've considered**

Right now I'm including the above snippet in a `custom.css` sheet.

**Comment by pradyunsg** [comment]
Thanks for filing this! ^>^

Would it make sense to have them be stylized like the "PARAMETERS", or is sticking to the regular make-it-bold sufficient?

**Comment by hoefling** [comment]
@pradyunsg I like both the capitalized and headings-like variants, the standard one (bold text) not so much. I think I would even prefer the capitalized headers over section headers, with "PARAMETERS" and "RETURN TYPE" fitting nicely as "yet another rubrics". But in the end, both are looking good, so it's up to you to decide :upside_down_face:

**Comment by hoefling** [comment]
At least for capitalized headers, I guess the change would be smth like

```sass
  p.rubric
    text-transform: uppercase
    font-size: var(--font-size--small)
```
in `src/furo/assets/styles/content/_api.sass`. At least it worked locally!

**Comment by pradyunsg** [comment]
Hehe. That's exactly what I intended to add. Wanna file a PR for it? ;)

**Comment by pradyunsg** [comment]
Actually, I'd make a new file for it. Nvm, I'll do it myself. 😅

**Comment by pradyunsg** [comment]
Oh hey, this was fixed in fa6b9bb958eb467530511f4f1ce5a6e710d1f7a8. I'll cut a release in a little bit.  :)

**Comment by hoefling** [comment]
@pradyunsg awesome, thank you! Waiting for the `b19` release :-)

**Comment by dvarrazzo** [comment]
Waiting for rubrics too: psycopg/psycopg3#14 :)

**Comment by pradyunsg** [comment]
Yup yup. I've relocated and started a new job, so my days are a little long. I'll get to this as soon as I'm able to make the time. :)

FWIW, I "just" have to run `nox -s release`, so it won't take too long once I get some time.

**Comment by pradyunsg** [comment]
Released the fix as part of beta 19. Let me know if that's not good-enough. :)
