### ISSUE TITLE
Allow for Contents header depth to be specified

### ISSUE THREAD

**Issue by Br4nd0R** [pradyunsg/furo#34]
It would be nice if there was a way to customize the depth of headers you want displayed in the contents bar of a given page.

For example, the below image shows the contents from a reference section of documentation.
![Screen Shot 2020-11-19 at 3 09 16 PM](https://user-images.githubusercontent.com/6100538/99735333-4c090100-2a79-11eb-8b50-41173887bc05.png)

I would like to be able to only list the top-level headers and not see the subheaders (command syntax, and options).

**Comment by pradyunsg** [comment]
Thanks for filing this! ^.^

On the one hand, I totally understand why this would be useful.

On the other hand, currently Furo is basically using the Sphinx-provided markup directly which provides the entire TOC without any configurability.

Enabling this would be a fairly significant chunk of complexity, which I'm not too excited by. Similar feelings for some "make a choice" discussions (per page vs site-wide) around adding any configuration knob like this as well. There's a hidden cost to adding configuration options and I'd like to treat that as pretty high for Furo.

Maybe you would want to use [Rubrics](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-rubric), once they get stylised properly (per #33) to avoid unwanted headings being added into the TOC for a page, but still being visually title-like?

**Comment by pradyunsg** [comment]
Relevant line of code, in the theme's markup: https://github.com/pradyunsg/furo/blob/fa726f7471270e27e8a2ac32f7423e492426bc0b/src/furo/theme/page.html#L133

**Comment by Br4nd0R** [comment]
Thanks, I will take a look!

**Comment by pradyunsg** [comment]
@Br4nd0R I reckon Rubrics are the way to go here. I'll add proper support in the next release -- which should be over the weekend.

Do feel free to reopen if you disagree (assuming GitHub lets you). :)
