### ISSUE TITLE
Assets hash change

### ISSUE THREAD

**Issue by dvarrazzo** [pradyunsg/furo#38]
**Describe the bug**
The `furo_asset_hash` variable changes hashes for the same resource in the same build.
 
**To Reproduce**

1. build any docs
2. `grep furo.css docs/_build/html/*.html | head`
```
docs/_build/html/adaptation.html:      <link rel="stylesheet" href="_static/styles/furo.css?state=cee7d01cd83c5f569d94bbb7">
docs/_build/html/connection.html:      <link rel="stylesheet" href="_static/styles/furo.css?state=11c4ff532c780a855f77bef8">
docs/_build/html/cursor.html:      <link rel="stylesheet" href="_static/styles/furo.css?state=b71df5d38afc2bca89011307">
docs/_build/html/errors.html:      <link rel="stylesheet" href="_static/styles/furo.css?state=898b0ed01020906787d65ca4">
docs/_build/html/from_pg2.html:      <link rel="stylesheet" href="_static/styles/furo.css?state=dce1277c6407b08d176e7d16">
docs/_build/html/genindex.html:      <link rel="stylesheet" href="_static/styles/furo.css?state=c09859bfc41dac5b6e5709be">
```
**Expected behavior**
The hash of the resource shouldn't change.

**Additional context**
```
pip freeze | grep furo
furo==2020.11.19b18
```

**Comment by pradyunsg** [comment]
I've played with this code so much. 😂

I think the asset hash needs to be generated on import and set into a global, instead of generating a new one on each call from html-context.

PRs welcome if you can get to this before I can!

**Comment by dvarrazzo** [comment]
Fixing
