### ISSUE TITLE
Add support for site-wide announcement banners

### ISSUE THREAD

**Issue by sethmlarson** [pradyunsg/furo#4]
Requesting ability for an html document to be inserted at the top of each page.
Would be nice for both announcements and warnings/redirects if you're on an old / deprecated version of the software.

**Comment by pradyunsg** [comment]
https://squidfunk.github.io/mkdocs-material/getting-started/ -- something like the black banner on top of this page?

**Comment by sethmlarson** [comment]
Yes that looks great!

**Comment by pradyunsg** [comment]
@sethmlarson Would it be OK to set something like the following?

```python
html_theme_options = {
    "announcement": "This is HTML text that you can put into your documentation, with inline tags like <b>bold</b> and more!"
}
```

**Comment by sethmlarson** [comment]
Yes that would work for our use-case.

**Comment by pradyunsg** [comment]
@sethmlarson Does the following look OK? Colours are customizable, text is centered until it goes too-wide, in which case it'll seem left aligned whilst being scrollable horizontally.

<img width="1440" alt="Screenshot 2020-09-09 at 1 38 30 AM" src="https://user-images.githubusercontent.com/3275593/92523018-443d0d00-f23d-11ea-960d-dfbea07acadb.png">

<img width="516" alt="Screenshot 2020-09-09 at 1 39 01 AM" src="https://user-images.githubusercontent.com/3275593/92523025-4737fd80-f23d-11ea-8de6-a43555ae5d1e.png">

<img width="377" alt="Screenshot 2020-09-09 at 1 38 46 AM" src="https://user-images.githubusercontent.com/3275593/92523021-456e3a00-f23d-11ea-8f4b-d6e6abc3342f.png">

**Comment by pradyunsg** [comment]
Oh boi, I'm gonna have to tweak how the header works on mobile. :)

**Comment by sethmlarson** [comment]
Looks good to me :)

**Comment by pradyunsg** [comment]
Done in 6f9f482fc55d7e81c07ea57fb51f370842ce41cd. :)
