### ISSUE TITLE
Add Furo examples

### ISSUE THREAD

**Issue by pauloxnet** [pradyunsg/furo#40]
**URL**: https://pradyunsg.me/furo/

**What is missing or inaccurate about the content on this page?**

Add a list of projects that are using Furo theme template, to show various example of Furo utilizations and promote it.

Example:
- [urllib3](https://urllib3.readthedocs.io)
- [psycopg3](https://www.psycopg.org/psycopg3/docs/)

**Comment by hugovk** [comment]
* https://pip.pypa.io/en/latest/ (not yet on stable)
* https://www.attrs.org/
* https://nox-poetry.readthedocs.io/
* https://doex.rohitsanjay.com/

**Comment by pradyunsg** [comment]
And https://packaging.pypa.io/en/latest/. ;)

**Comment by pradyunsg** [comment]
https://github.com/pradyunsg/furo#used-by :)

**Comment by pauloxnet** [comment]
Thanks.

**Comment by stonecharioteer** [comment]
These look so great. :)
