### ISSUE TITLE
Dark mode toggle in the right-hand sidebar

### ISSUE THREAD

**Issue by ddelange** [pradyunsg/furo#44]
**Is your feature request related to a problem? Please describe.**
Google Chrome (Mac OS X) respects system wide dark mode setting. However, the tab bar becomes barely readable for me when Chrome is in dark mode, so I [disabled dark mode for Chrome](https://superuser.com/a/1418041/966286).

Quoting furo [docs on dark mode](https://pradyunsg.me/furo/customisation/colors/#how-light-and-dark-mode-work), it seems I won't be able do view dark furo projects without putting my whole browser in dark mode (unwanted):
> Furo is in light mode by default, switching to the dark mode when requested by the user’s browser (through `prefers-color-scheme: dark`).
> 
> As a consequence of this design, the dark mode inherits the variable definitions from the light mode, only overriding specific values to adapt the theme. While the mechanism for switching between light/dark mode is not configurable, the exact CSS variable definitions used in this process can be configured.

**Describe the solution you'd like**
A nice solution would be to keep this behaviour, but to additionally give the user the option to override the CSS prop with a toggle, like for instance [Docker docs](https://docs.docker.com/) have on every page.

**Describe alternatives you've considered**
Alternatively, I could somehow attempt hack my Chrome set up to [emulate](https://web.dev/prefers-color-scheme/#emulating-prefers-color-scheme-in-devtools) this CSS prop on all websites by default, essentially putting my Chrome in dark mode only for the content and not for Chrome's own UI.

**Additional context**
Docker docs example dark mode toggle on the right:
![image](https://user-images.githubusercontent.com/14880945/100444225-64959e80-30ab-11eb-851e-7509fe336d55.png)

**Comment by pradyunsg** [comment]
Same as #24. :)
