### ISSUE TITLE
Add a "view this page" link

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/furo#478]
### What's happening?

Currently, Sphinx sites built with Furo do not provide any links to view the sources. This previously existed as a part of the footer, but users found it confusing that things didn't "just work" (it used Sphinx's copied sources, unconditionally).

### Reproducer

1. Build any Sphinx documentation set with Furo.
2. Visit any page on the built site.
3. Notice the lack of links to view the sources of the current page.

### Expectation

Design wise, this can sit beside the "edit this page" link, and should support all the same things as that.

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/pradyunsg/furo/blob/main/CODE_OF_CONDUCT.md).

**Comment by LuisBL** [comment]
this alablaster feature is realy missing

**Comment by marxin** [comment]
Hopefully #528 gets merged soon.

**Comment by eine** [comment]
Ref: #630.

**Comment by LuisBL** [comment]
Any news on this ?
My team request this feature (that help to speedup the markdown/restructuredtext syntax adoption that they are ready to leave furo just to get it back.

**Comment by pradyunsg** [comment]
Done in https://github.com/pradyunsg/furo/commit/2ce7e89cb799bcb1312b711b17fca90d2979fa21

I'll cut a release at some point this month.
