### ISSUE TITLE
Generated index pages don't render

### ISSUE THREAD

**Issue by gilch** [pradyunsg/furo#50]
**Describe the bug**

The generated index, module index, and search pages don't render.
The search page has the sidebar, but the other two are completely blank.

**To Reproduce**

Add these refs to your index page (`sphinx-quickstart` adds these automatically).
```
* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
```
Set `html_theme = 'furo'` in `conf.py`.
Generate Sphinx docs with `make html`.
Open in browser and click on each link from these refs.

**Expected behavior**

If you remove the `html_theme = 'furo'` in `conf.py` it renders with the default alabaster theme. When you click these three links, you get to their corresponding pages and they're not blank. Furo's generated pages should have the same content, but with different styling.

**Desktop (please complete the following information):**

Tested on Microsoft Edge.

**Comment by pradyunsg** [comment]
Oh well. Looks like I forgot to add the templates for them! :)

**Comment by wlupton** [comment]
I've hit this too (using the latest from pypi, i.e., 2020.12.30b24). For me the index and search page work, but not the module index. I'd be happy to take a look at fixing it but would appreciate a pointer, e.g., which templates and where are they? Thanks.

**Comment by pradyunsg** [comment]
Well, someone needs to populate the domain index html template. I haven't come around to it yet, but PRs are welcome! :)

**Comment by wlupton** [comment]
I found `domainindex.html` and tried putting some content in there but (assuming I did the right thing with `gulp` and `pip`) didn't see any change. I'm afraid I don't know enough to be able to work out how and where it's being used. Any hints? Thanks!

**Comment by pradyunsg** [comment]
@wlupton Hi! Apologies for the delayed response. Have you seen https://pradyunsg.me/furo/contributing/workflow/?

I'm personally not a 100% sure how the index pages are generated by Sphinx, so if someone who uses/knows more about them could chime in, that'd be great! :)

**Comment by pradyunsg** [comment]
I'm personally not a 100% sure how the index pages are generated by Sphinx, so if someone who uses/knows more about them could chime in, that'd be great!

**Comment by wlupton** [comment]
I looked at this again and (this time) tried replacing domainindex.html with (more-or-less) the sphinx-doc/sphinx version (editing it to extend base.html rather than layout.html). This seems to work.

I created PR #91. As noted there, more work may be needed to integrate it into the theme, but it seems to work.

**Comment by pradyunsg** [comment]
8b3325ea6986453bffd391b1a98f3d91bcb9af40 should fix this. :)
