### ISSUE TITLE
Should large images get special treatment?

### ISSUE THREAD

**Issue by AWhetter** [pradyunsg/furo#51]
**Is your feature request related to a problem? Please describe.**

Currently a large image is placed in the documentation by resizing it down with a simple `max-width: 100%; height: auto`. For images containing text this can often leave the text unreadable, especially on smaller devices.

Should this be something that an author should be expected to handle (ie get them to supply a `:target:` to the image directive that links to the image, which would open the image in a new tab), or should the theme be able to handle the problem or at least assist with it?

**Describe the solution you'd like**

If the theme were to deal with it, my preferred approach would be option 1 as described below

**Describe alternatives you've considered**

1. Do a "simple zoom" when clicked on. For example: https://github.com/francoischalifour/medium-zoom
  1a. This only really works for images up to a certain size but I don't think it's unreasonable for an author to have to deal with this situation.
2. Have a "zoom" button that shows over a resized image when hovered over. When clicked, the image is opened in some overlay. The downside here is that it would require some javascript in a theme that otherwise works well without it.
  2a. Just opening the image sized to the window would be an improvement but this approach would inevitably lead to feature requests for adding zoom and pan controls.
3. Don't resize the image and instead have a max-height and `overflow: scroll`. I think that the scroll bars would add visual clutter though.
  3a. This situation is difficult to deal with as an author because whether scroll bars are appropriate or not would vary depending on the image content, the size of the image, and the screen size. We could pick scrolls bars or not depending on the screen size, but I think it's impossible to map media queries to match all cases.

**Additional context**

None.

**Comment by pradyunsg** [comment]
> 2\. Have a "zoom" button that shows over a resized image when hovered over.

This won't help on small displays.

> Should this be something that an author should be expected to handle (ie get them to supply a `:target:` to the image directive that links to the image, which would open the image in a new tab), or should the theme be able to handle the problem or at least assist with it?

For anyone wondering what they can provide to various directives: https://docutils.sourceforge.io/docs/ref/rst/directives.html#image

I think a good approach would be to create a Sphinx plugin that can be added into their documentation by projects that care. :)

**Comment by pradyunsg** [comment]
Closing since I don't think that there should be any special casing in Furo, but doing it in an additional Sphinx plugin would be great!
