### ISSUE TITLE
pygments_dark_style doesn't work?

### ISSUE THREAD

**Issue by jreese** [pradyunsg/furo#52]
**URL**: https://pradyunsg.me/furo/customisation/colors/#code-block-styling

**What is missing or inaccurate about the content on this page?**

This section suggests using a Pygments option for Sphinx that doesn't exist, and it seems that no matter what I set this value to, Furo uses its own color scheme for code segments in dark mode.

Is there a known-working mechanism for choosing the Pygments style used in dark mode, or does this require overriding the dark mode CSS variables in the Fure stylesheet?

**Comment by dgw** [comment]
Same as #49, I believe.

**Comment by jreese** [comment]
I swear I looked at all the open issues and yet I didn't see that one 😅

**Comment by dgw** [comment]
It happens to all of us! 🙈
