### ISSUE TITLE
Highlights for target anchors

### ISSUE THREAD

**Issue by inducer** [pradyunsg/furo#53]
Clicking this link will highlight the definition linked by the anchor:

https://docs.python.org/3/library/functools.html#functools.partial

Clicking this link does not currently highlight the definition linked by the anchor:

https://documen.tician.de/pyopencl/runtime_queue.html#pyopencl.CommandQueue

(generated with Furo 2020.12.9b21 according to [this build log](https://gitlab.tiker.net/inducer/pyopencl/-/jobs/205043#L86))

**Describe the solution you'd like**

There should be anchor highlighting just like for the majority of other sphinx themes. (default, alabaster, ...).

**Comment by pradyunsg** [comment]
Fixed in fc05d0623a12581b31f55d8ff4380e7044d348ee. :)

**Comment by inducer** [comment]
Thanks! (And thanks for your work on this beautiful theme!)

**Comment by pradyunsg** [comment]
FYI: The fix is a part of the beta22 release that I made earlier today. :)
