### ISSUE TITLE
Broken link in Markup Reference->Code Blocks

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/furo#593]
### Discussed in https://github.com/pradyunsg/furo/discussions/591

<div type='discussions-op-text'>

<sup>Originally posted by **ivergara** December  7, 2022</sup>
In the [documentation](https://pradyunsg.me/furo/reference/code-blocks/) concerning code blocks, the link at the end pointing to https://myst-parser.readthedocs.io/en/latest/using/intro.html#block-level-directives-with-myst-markdown is broken as in that anchor doesn't exist.</div>

### What's broken?

https://pradyunsg.me/furo/reference/code-blocks/ has a broken link, pointing to https://myst-parser.readthedocs.io/en/latest/using/intro.html#block-level-directives-with-myst-markdown

### What's the fix?

Fixing the broken link, by pointing to the relevant location in myst-parser's documentation about block level directives. It's likely moved as part of a documentation update.

**Comment by DiddiLeija** [comment]
Hi! Does https://myst-parser.readthedocs.io/en/latest/intro.html#extend-commonmark-with-roles-and-directives cover what is needed? Or probably https://myst-parser.readthedocs.io/en/latest/syntax/roles-and-directives.html?

**Comment by pradyunsg** [comment]
The later seems like a better fit, since it's less in-the-flow for some other content and covers what we want at the start! :)

**Comment by DiddiLeija** [comment]
Oh, nice! I'll come back with the fix ;)

**Comment by DiddiLeija** [comment]
Done! #595
