### ISSUE TITLE
Search is endless looping with Sphinx 3.4.1

### ISSUE THREAD

**Issue by dbitouze** [pradyunsg/furo#62]
**Describe the bug**
Search is endless looping with Sphinx 3.4.1.

**To Reproduce**
1. Create a minimal Sphinx 3.4.1 documentation with:

- as `conf.py`, the same as default, except of course `html_theme = 'furo'` instead of `html_theme = 'alabaster'`:
```Python
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Test 3.4.1'
copyright = '2020, Denis Bitouzé'
author = 'Denis Bitouzé'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = 'furo'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
```
- as `index.rst`, almost the default one:
```rst
.. Test 3.4.1 documentation master file, created by
   sphinx-quickstart on Sat Dec 26 14:09:47 2020.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to Test 3.4.1's documentation!
======================================

.. toctree::
   :maxdepth: 2
   :caption: Contents:

This a title
============

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
```

2. Run `make html`.
3. Open the `index.html` resulting file in any Web browser.
4. Search e.g. "title".

The searching will endless loop on: "Searching", "Searching.", "Searching..", "Searching...".

**Expected behavior**
Search works as expected.

**Desktop (please complete the following information):**

- OS: Linux Mageia 7
- Browsers: Firefox, Chromium, GNOME Web, Midori
- Version: furo 2020.11.27.beta19 or furo 2020.12.9b21

**Additional context**
Search is working as expected with:

- Sphinx 3.3.1 and Furo,
- Sphinx 3.4.1 and Alabaster.

**Comment by idnsunset** [comment]
Same issue confirmed with 3.4.1, and the "Stemmer is not defined" error appears again.

**Comment by pradyunsg** [comment]
Can you try with the current master branch, and confirm if this is still an issue?

**Comment by dbitouze** [comment]
> Can you try with the current master branch, and confirm if this is still an issue?

I installed `furo` thanks to `pip3` and also cloned locally its `GitHub` cloned repository. But could you explain how to tell `Sphinx` to use not the former but the latter?

**Comment by dbitouze** [comment]
BTW, I guess the current master branch is the one called `main`, isn't it?

**Comment by pradyunsg** [comment]
Yea, sorry, the current main branch, yea.

**Comment by pradyunsg** [comment]
To install furo from the git repository, from the root of the git repository, you'll want to do:

```
npm install
gulp build
pip install .
```

That should install it in the current pip environment.

**Comment by dbitouze** [comment]
> To install furo from the git repository, from the root of the git repository, you'll want to do:
> 
> ```
> npm install
> gulp build
> pip install .
> ```
> 
> That should install it in the current pip environment.

I had to install `gulp` independently (and as `root`). Otherwise, it was correctly installed.

**Comment by dbitouze** [comment]
> Can you try with the current master branch, and confirm if this is still an issue?

It looks like it works nicely, now: thanks!

When could we expect a new (at least `furo-2020.12.9.dev22`) release fixing this issue?

**Comment by pradyunsg** [comment]
Once my new monitor arrives later today, to so that I can use my laptop-with-a-broken-display again. :)
