### ISSUE TITLE
Make "Search" customizable or, better, automatically translated

### ISSUE THREAD

**Issue by dbitouze** [pradyunsg/furo#66]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be nice for the placeholder "Search" to be customizable or, better, to be automatically translated according to the chosen language for the underlying Sphinx documentation.

**Comment by pradyunsg** [comment]
Which Search are you referring to?

The "Search" in the title is translatable:

https://github.com/pradyunsg/furo/blob/35f47a9b4fc93ad4146d59c6e2fea932be7cb1fa/src/furo/theme/search.html#L10

Please elaborate further on what exactly you want to achieve -- I imagine it's either (a) possible with Sphinx's internationalization support, or (b) something that I missed while writing the templates. :)

**Comment by dbitouze** [comment]
> Which placeholder are you referring to?
> 
> The "Search" in the title is translatable:
> 
> https://github.com/pradyunsg/furo/blob/35f47a9b4fc93ad4146d59c6e2fea932be7cb1fa/src/furo/theme/search.html#L10

And I guess it is indeed since, in my Sphinx documentation which is set up in French:
```html
<link rel="search" title="Recherche" href="search.html" />
```
> Please elaborate further on what exactly you want to achieve -- I imagine it's either (a) possible with Sphinx's internationalization support, or (b) something that I missed while writing the templates. :)

:smile:

In the Sphinx side of my documentation everything is properly translated. But not the "Search" string which appears in the search form (see `placeholder="Search"`):

```html
<form class="sidebar-search-container" method="get" action="search.html">
  <input class="sidebar-search" placeholder="Search" name="q">
  <input type="hidden" name="check_keywords" value="yes">
  <input type="hidden" name="area" value="default">
</form>
```

**Comment by pradyunsg** [comment]
Ah indeed. Nice catch!

https://github.com/pradyunsg/furo/blob/main/src/furo/theme/sidebar/search.html -- do you want to file a PR wrapping the Search string in the placeholder? If not, lemme know and I'll do it myself. :)

**Comment by dbitouze** [comment]
PR filed :smile:
