### ISSUE TITLE
Add `dirhtml` special-case handling for canonical URLs

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/furo#682]
Discussed in https://github.com/pradyunsg/furo/discussions/656

https://github.com/sphinx-doc/sphinx/issues/9730 is the upstream issue about how the dirhtml builder with Sphinx is buggy when used with dirhtml pages, and generates incorrect URLs.

Other Sphinx themes have been working around this bug:

- [Sphinx RTD](https://github.com/readthedocs/sphinx_rtd_theme/blob/6beecce44759257ed584f2fdb0357f2aec0ad01a/sphinx_rtd_theme/layout.html#L62-L77)
- [Sphinx awesome](https://github.com/kai687/sphinxawesome-theme/pull/1262)

**Comment by davidism** [comment]
Pallets-Sphinx-Themes as well: https://github.com/pallets/pallets-sphinx-themes/blob/7a6fa47323af403c19008a5df8b5302a1ead7be3/src/pallets_sphinx_themes/__init__.py#L72-L91

**Comment by pradyunsg** [comment]
Furo also assumes that its an extension, and relies on that. That actually seems like a cleaner fix -- thanks for sharing that @davidism! :)

**Comment by skrawcz** [comment]
@pradyunsg is there any movement on this? I just realized that this bug impacts your google SEO so I'd love to have it fixed. Let me know how I can help -- and thanks for the theme!

**Comment by pradyunsg** [comment]
A PR for this would be welcome! I've had limited OSS tim lately.

**Comment by skrawcz** [comment]
> A PR for this would be welcome! I've had limited OSS time lately.

yep -- would you be able to point me in the right direction please? I have limited bandwidth too, and really what I need help is knowing where I should be looking modify and in how many places etc., since I don't know the code base that well.

**Comment by davidism** [comment]
I don't mind doing this at the end of the week when I'm home for vacation, I'll base it on my solution from pallets I posted above.

**Comment by skrawcz** [comment]
> I don't mind doing this at the end of the week when I'm home for vacation, I'll base it on my solution from pallets I posted above.

Awesome thanks. I'm happy to help validate the fix if that's helpful.

**Comment by skrawcz** [comment]
> I don't mind doing this at the end of the week when I'm home for vacation, I'll base it on my solution from pallets I posted above.

@davidism *bump* happy to test when you have something up please! :)

**Comment by skrawcz** [comment]
@davidism @pradyunsg sorry -- I didn't actually validate the URL 🤦  -- I just validated that the `.html` was gone.

So to me the URL is still incorrect, or I have something incorrect in my sphinx set up.

E.g. 

Go to https://hamilton.dagworks.io/en/latest/concepts/hamilton-function-structure/

you'll see the following in the HTML:
```html
<link rel="canonical" href="https://hamilton.dagworks.io/concepts/hamilton-function-structure/">
```
However that URL leads to a 404 because it is missing the `en/latest/` part in the URL. So question -- is this expected? Or do I have sphinx incorrectly configured here and instead it should redirect appropriately?

**Comment by skrawcz** [comment]
Okay I have a PR up that fixes this - https://github.com/pradyunsg/furo/pull/733
