### ISSUE TITLE
My docs won't build on master

### ISSUE THREAD

**Issue by gilch** [pradyunsg/furo#69]
**Describe the bug**

Sphinx docs fail to build with Furo. The error message is:
```
Theme error:
An error happened in rendering the page index.
Reason: FileNotFoundError(2, 'No such file or directory')
```

**To Reproduce**

In a new virtual environment, use `pip install` on
```
sphinx==3.1.2
git+https://github.com/pradyunsg/furo@d5df1d4d07eb01ae49e50bbbb6d0fa6c6e6dd9fa
```
Make a docs folder somewhere, and inside it run `sphinx-quickstart`. The defaults are fine. Name/Author/Release can be `Furo` or whatever.

Run `make html`, and the new docs should build with the default "alabaster" theme.

Change the `html_theme = 'alabaster'` line in the `conf.py` that the quickstart generated to `html_theme = 'furo'` instead.

Run `make html` again. You should see the error message. The html docs are still alabaster.

**Expected behavior**
Docs should have built with the Furo theme.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Irrelevant, but Edge
- Furo Version: master (d5df1d4)

**Comment by pradyunsg** [comment]
> git+https://github.com/pradyunsg/furo@d5df1d4d07eb01ae49e50bbbb6d0fa6c6e6dd9fa

Furo is not usable directly from the VCS repository, since the compiled assets are not tracked (the final JS/CSS).

**Comment by pradyunsg** [comment]
FYI: To install the development version of Furo, you need to:

- clone the repository and `cd` into it.
- run `npm install`
- run `./node_modules/bin/gulp build`
- run `pip install .`

---

I don't plan on changing this at this time; and there's a lot of interesting discussion in https://github.com/executablebooks/meta/issues/137 about these things.

**Comment by pradyunsg** [comment]
Closing since I don't think there's anything actionable here at this time.

I'll be cutting a release soon, which would hopefully mean that you won't need to try pinning to a specific commit. :)
