### ISSUE TITLE
Sphinx 7.2.1 might be breaking things?

### ISSUE THREAD

**Issue by jkanche** [pradyunsg/furo#695]
### What's happening?

I was trying to debug whats causing the builds to fail between these two runs - [pass](https://github.com/BiocPy/scranpy/actions/runs/5883119066/job/15955088320) vs [fail](https://github.com/BiocPy/scranpy/actions/runs/5892740018/job/15982703950). it boils down to the new release of Sphinx, former using 7.1.2.

This is the error message in the console even though I don't have any `html_style` set in my configuration. 

```
Extension error (furo):
Handler <function _html_page_context at 0x7faf7425e940> for event 'html-page-context' threw an exception (exception: This documentation is not using `furo.css` as the stylesheet. If you have set `html_style` in your conf.py file, remove it.)
```

### Reproducer

failed build using sphinx 7.2.1

### Expectation

successful build using 7.1.2

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/pradyunsg/furo/blob/main/CODE_OF_CONDUCT.md).

**Comment by Eric-Arellano** [comment]
See https://github.com/pradyunsg/furo/discussions/693. Pradyun requests that people use discussions rather than issues because they like to use issues only for project tracking. I recommend closing this and moving to https://github.com/pradyunsg/furo/discussions/693.

**Comment by jkanche** [comment]
Sorry did not see the discussion tab. Thanks for pointing me to that.

**Comment by ReenigneArcher** [comment]
I get the same thing with **Sphinx 7.0.1** and **Furo 2023.8.19**.

```txt
sphinx.errors.ConfigError: This documentation is not using `furo.css` as the stylesheet. If you have set `html_style` in your conf.py file, remove it.

Configuration error:
This documentation is not using `furo.css` as the stylesheet. If you have set `html_style` in your conf.py file, remove it.
```

**Comment by jkanche** [comment]
> I get the same thing with **Sphinx 7.0.1** and **Furo 2023.8.19**.
> 
> ```
> sphinx.errors.ConfigError: This documentation is not using `furo.css` as the stylesheet. If you have set `html_style` in your conf.py file, remove it.
> 
> Configuration error:
> This documentation is not using `furo.css` as the stylesheet. If you have set `html_style` in your conf.py file, remove it.
> ```

This is fixed if you switch to the most recent versions of sphinx and furo.
