### ISSUE TITLE
RTD version selector not injected on some pages

### ISSUE THREAD

**Issue by sethmlarson** [pradyunsg/furo#7]
The search page receives the RTD version selector:
- https://urllib3.readthedocs.io/en/latest/search.html?q=a&check_keywords=yes&area=default

However as far as I can tell all RST pages don't receive the selector:
- https://urllib3.readthedocs.io/en/latest/sponsors.html

Potentially something to do with jQuery? From the Inspect Element Console:

```
Uncaught ReferenceError: $ is not defined
```

**Comment by pradyunsg** [comment]
Argh. Why does RTD want jquery? :(

**Comment by pradyunsg** [comment]
bea26d9 should fix this, by including the JS files that this theme doesn't use *at all*.

I was trying to avoid https://github.com/readthedocs/readthedocs.org/issues/7140, but I don't think it's possible, given the assumptions baked into the way ReadTheDocs handles versions. :)
