### ISSUE TITLE
`.highlight {overflow: auto}` issue in 2020.12.28.beta22

### ISSUE THREAD

**Issue by bastimeyer** [pradyunsg/furo#70]
**Describe the bug**
Introduced by 9496d05896b417001a2d25e95034a49b840b5912
This causes `code-block`s to overflow and stretch the content.

**To Reproduce**
Add `.. code-block:: bash` to a table cell and add a long text line to it

**Expected behavior**
The code block itself should have scollbars and should not overflow or stretch the content.

**2020.12.09.beta21**
The `.highlight` code has a proper `overflow: auto` property
![image](https://user-images.githubusercontent.com/467294/103225266-d7ec3380-4929-11eb-9adf-1f0957b1d565.png)

**2020.12.28.beta22**
The entire table is now stretched and has a vertial scrollbar instead (cut off from the screenshot), due to `.table-wrapper` from `_tables.sass` which also sets `overflow-x: auto`
![image](https://user-images.githubusercontent.com/467294/103225336-f81bf280-4929-11eb-849c-f3fad887905b.png)

**Comment by pradyunsg** [comment]
OH Interesting. I completely forgot about this.

**Comment by pradyunsg** [comment]
Fixed in f25c05da3587181d2b5ebc73d7fad284c01c9b52, and released as beta23. :)
