### ISSUE TITLE
Sphinx 6.2.1: hash digest injection is broken due to reuse of `css_files` in HTML context

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/furo#716]
### Discussed in https://github.com/pradyunsg/furo/discussions/708

Sphinx 6.2.1 reuses `css_files` across multiple files, which means that the injection of hash'd digests for assets fails due to the hash injection not being idempotent. This means that the build fails if there are more than one HTML files to generate.

**Comment by pradyunsg** [comment]
Until this is resolved, folks can change their requirement on Furo to: `furo != 2023.08.17, != 2023.08.19`. I'll yank those releases, once I have a release out with the fixes made.

**Comment by Eric-Arellano** [comment]
>  I'll yank those releases, once I have a release out with the fixes made.

This will break all the Qiskit projects that are pinned to an exact Furo version. If possible, it'd be great to not yank since it's possible to use a Sphinx x Furo combination that is valid. Since there isn't a security vulnerability, I'm not sure yanking would be necessary?

**Comment by pradyunsg** [comment]
Yanking doesn't break pinning based workflows. See https://pypi.org/help/#yanked.

**Comment by pradyunsg** [comment]
Fixed in https://pradyunsg.me/furo/changelog/#zesty-zaffre

**Comment by pradyunsg** [comment]
<img width="675" alt="Screenshot 2023-09-10 at 17 03 49" src="https://github.com/pradyunsg/furo/assets/3275593/263375bd-0b6b-4eb3-bccd-9aed7ccf2925">
