### ISSUE TITLE
Document how to add custom JS to pages

### ISSUE THREAD

**Issue by xuhdev** [pradyunsg/furo#72]
**Is your feature request related to a problem? Please describe.**
There's no (documented) way to conveniently insert tracking code.

**Describe the solution you'd like**
Add a block `{tracking_code}` in the template and allow user to specify it in `conf.py`. For example:

```python
tracking_code = '<script async defer data-domain="yourdomain.com" src="https://plausible.io/js/plausible.js"></script>'
```

**Describe alternatives you've considered**
Inherit the theme and make modifications. But given the frequency of using this feature, inheriting a theme to insert a tracking code seems overkilling.

**Comment by pradyunsg** [comment]
Thanks for filing this issue!

I don't think Furo needs to directly add support for injecting custom tracking code like this. It's straightforward enough to extend templates with Sphinx, and that's (IMO) the correct mechanism to add site-specific HTML/CSS/JS.

Here's an example of how to do that, from a repository that's extending Furo to add additional content to their documents' `<head>`: https://github.com/streamlink/streamlink/blob/17a4088c38709123c0bcab4a150549bd16d19e07/docs/_templates/base.html

---

If you reckon how-to-do-this is not straightforward enough to understand, lemme know and I'll look into adding a page to the Customisation section of Furo's documentation.

**Comment by xuhdev** [comment]
Thanks, it seems like `extrahead` is the most pragmatic place to insert tracking code. Yeah, I agree some documentation should be sufficient.

**Comment by pradyunsg** [comment]
Done in https://github.com/pradyunsg/furo/commit/07cec3f862a360ad9c4046c21f5c8190bb68a1fa
