### ISSUE TITLE
希望 ON THIS PAGE 处的滚动条可以被隐藏

### ISSUE THREAD

**Issue by Modnars** [pradyunsg/furo#742]
### What's happening?

当 ON THIS PAGE 处的内容过多时，会有一个滚动条，但这个滚动条本身是不会隐藏的，而非系统可设置的滚动时显式。希望页面静止时，不要显式这个滚动条，不然很不美观、很突兀。
![image](https://github.com/pradyunsg/furo/assets/22772190/4eba4a6d-5956-4955-8b19-84a09101405d)

### Reproducer

当页面的标题内容比较多时，右侧 ON THIS PAGE 就可以稳定复现这个问题。
如有需要，也可以直接访问 https://learning.modoo.zone/csapp/Part02/Ch09.html 来查看现象。

### Expectation

滚动条在页面静置时不应该显式。

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/pradyunsg/furo/blob/main/CODE_OF_CONDUCT.md).

**Comment by pradyunsg** [comment]
Please open a discussion for this: https://github.com/pradyunsg/furo/issues/477
