### ISSUE TITLE
Formatting for the :guilabel: role

### ISSUE THREAD

**Issue by Helveg** [pradyunsg/furo#75]
**Is your feature request related to a problem? Please describe.**
The `:guilabel:` role has no formatting in the Furo theme, it is formatted as regular text and does not stand out in any way.

**Describe the solution you'd like**
In other themes the `:guilabel:` is usually formatted as something that looks like a keyboard key or some sort of label.

**Comment by pradyunsg** [comment]
Added in 4ea77e714057bd052ef61f50493c5eb4b18ed9fb. :)
