### ISSUE TITLE
Dark theme not taken in account on computer

### ISSUE THREAD

**Issue by dbitouze** [pradyunsg/furo#76]
**Describe the bug**
The dark theme of Firefox browser is not taken in account on computer, as shown by the following screenshots, but is taken in account on smartphone.

**Screenshots**

- Firefox on computer
![image](https://user-images.githubusercontent.com/1032633/106285094-577c6380-6244-11eb-9997-23e3dcd37c57.png)
- Firefox on smartphone
![Screenshot_2021-01-29-15-25-45-78_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/1032633/106287651-50a32000-6247-11eb-8cd7-a415f808a6a6.jpg)
- Firefox on smartphone (computer version)
![Screenshot_2021-01-29-15-36-22-28_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/1032633/106288168-f8b8e900-6247-11eb-8982-21845b970ece.jpg)

**Desktop (please complete the following information):**

- OS: Linux Mageia 7
- Browser:  Firefox 85.0 (the same happens with Chromium 87.0.4280.141)
- Version: ?

**Smartphone (please complete the following information):**

- Device: OPPO A9 2020
- OS: ColorOS 7.1
- Browser: Firefox 85.1.1 (the same happens with Chromium 89.0.4324.93)
- Version: ?

**Comment by pradyunsg** [comment]
Thanks for filing an issue, while also completing the issue template! Much appreciated! ^.^

The dark mode depends on your browser-provided `prefers-color-scheme` CSS media query. I'd suggest looking into why that's not being set to `dark` for you, on your PC. It's usually a system

**Comment by pradyunsg** [comment]
Closing since I don't think there's anything actionable here.

**Comment by dbitouze** [comment]
> Closing since I don't think there's anything actionable for Furo here.

I tried to set a dark mode on my system (KDE Plasma) but this hasn't any effect on Furo.
