### ISSUE TITLE
Search broken on RTD

### ISSUE THREAD

**Issue by jta** [pradyunsg/furo#77]
**Describe the bug**
Furo on barebones readthedocs hosted docs leads to the following error occasionally being triggered on search pages:

```
readthedocs-doc-embed.js:1 Uncaught ReferenceError: $ is not defined
    at Object.get (readthedocs-doc-embed.js:1)
    at Object.init (readthedocs-doc-embed.js:1)
    at n (readthedocs-doc-embed.js:1)
get @ readthedocs-doc-embed.js:1
init @ readthedocs-doc-embed.js:1
n @ readthedocs-doc-embed.js:1
setTimeout (async)
19../doc-embed/footer.js @ readthedocs-doc-embed.js:1
c @ readthedocs-doc-embed.js:1
o @ readthedocs-doc-embed.js:1
(anonymous) @ readthedocs-doc-embed.js:1
```

Changing to base theme or sphinx_press_theme works fine. No extensions are loaded. Sphinx 3.4.0.

**To Reproduce**

1. Open https://docs.observeinc.com/en/joao-test/search.html?q=test_string

This page will either:
- load a page stating no search results were found
- blank screen due to reported console error

Opening page in incognito mode seems to trigger this more often than not.

**Desktop**

- OS: OSX
- Browser: Chrome and Safari

**Comment by pradyunsg** [comment]
This should be fixed by the changes I've pushed to this repo on Feb 1st. I need to cut a release though, so I'll keep this open so I don't forget. :)

**Comment by pradyunsg** [comment]
This should be fixed with beta25. Could you confirm?

**Comment by jta** [comment]
Appears to be fixed, thanks! 💯
