### ISSUE TITLE
Broken CSS on sidebar ToC subsection reveal

### ISSUE THREAD

**Issue by McSinyx** [pradyunsg/furo#8]
The subsection revealed doesn't look right:

![2020-09-11T17:14:55](https://user-images.githubusercontent.com/13689192/92912614-28f81a80-f454-11ea-97b6-46742e6d4c46.png)

Step to reproduce:

1. Open [any site using this theme and having nested ToC](https://urllib3.readthedocs.io/en/latest/index.html)
2. Click on that section

My guess would be there's something wrong with CSS but I don't know for sure.

Off-topic: Congrats on getting furo adopted by urllib3!  Overall I like the esthetic (the color, line break after **Parameters** in `:function:`, etc.), so feed me with updates on Twitter!

**Comment by pradyunsg** [comment]
What browser? What OS?

**Comment by McSinyx** [comment]
I'm sorry for not included such information.  I'm on Firefox 68.11.0esr on Debian GNU/Linux testing on amd64.  I can reproduce on neither Firefox 80.0.1 (via flatpak) nor Chromium 83.0.4103.116 (also from Debian) though.

**Comment by pradyunsg** [comment]
Yea, at less that ~0.16% market share from a really outdated browser, I think I'm not gonna bother.

**Comment by McSinyx** [comment]
:shrug: I'm going to wait for [ESR 78](https://packages.debian.org/search?keywords=firefox-esr) to land to testing then, hopefully before furo hits its first stable release.
