### ISSUE TITLE
Provide a simple way to hide the highlighting of search results

### ISSUE THREAD

**Issue by dbitouze** [pradyunsg/furo#81]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when, after a search, the text is cluttered by the highlighting of search results (this is notably the case when what I'm looking for is a given document that I search with some words of its title).

**Describe the solution you'd like**
I'd like `Furo` to provide a simple way to hide the highlighting of search results as it is the case in the `Sphinx-doc`documentation (see for instance at the bottom right of [this page](https://www.sphinx-doc.org/en/master/index.html?highlight=Sphinx)).

**Describe alternatives you've considered**
Some themes support this feature, for instance the [Insipid Sphinx Theme](https://insipid-sphinx-theme.readthedocs.io/en/0.2.2/index.html) as one can see at the top of [this page](https://insipid-sphinx-theme.readthedocs.io/en/0.2.2/configuration.html?highlight=Sphinx#sphinx-settings) (click on "Hide Search Matches").

**Comment by pradyunsg** [comment]
Ah interesting! It looks like a simple:

```
<a href="javascript:Documentation.hideSearchWords()">Hide Search Matches</a>
```

The big question is, where should this go on the page layout. :)

**Comment by dbitouze** [comment]
> The big question is, where should this go on the page layout. :)

I like it at the top of the page (as with the Insipid Sphinx Theme) since you may want to look for a given document (searched with some words of its title) and not individual words. In such cases, you want to hide the searched words as soon as you reach the expected page.

Moreover, when it isn't at the top of the page, as it is the case  in the `Sphinx-doc` documentation, the link that hides the searched words may be visible only if you scroll down, as in [this page](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=logo).

**Comment by pradyunsg** [comment]
Done in dfe43e8838549ddcdc6e47bc387d3ca2aa60480a. Will cut a release next weekend.

**Comment by pradyunsg** [comment]
You can try it out here: https://pradyunsg.me/furo/reference/tables/?highlight=table
