### ISSUE TITLE
Transparent SVG shown as white background when use ..raw:: 

### ISSUE THREAD

**Issue by KettyKuutvuori** [pradyunsg/furo#816]
### What's happening?

When embedding transparent SVG with text content in documentation with `.. raw:: html <object data=image-path type="image/svg+xml"></object>` A white background is shown despite the file having a transparent background. The same image will show a transparent background as expected when embedded with `.. image::`. 

This happens after we update the Furo theme. Is it possible to embed SVG with text by using` .. raw::` html and won't have a white background? 

![svg-testing-2023 version](https://github.com/user-attachments/assets/5a958029-35b5-4ade-a123-45e17ca0b00e)
![test-svg-code-2023](https://github.com/user-attachments/assets/f02fb7e4-068d-45dc-9c21-923088cdfc00)
As expected, the same image will show a transparent background 

### Reproducer

1. Build Sphinx documentation at 'visual studio'
2. Go to 'terminal' build document '.\make.bat html'
3. Click on the build document link
4. Check the images embedded 

### Expectation

When embedding transparent SVG with text content with `.. raw:: html`, the background should behave as its original design. 

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/pradyunsg/furo/blob/main/CODE_OF_CONDUCT.md).

**Comment by pradyunsg** [comment]
Please do not file an issue as noted in https://github.com/pradyunsg/furo/issues/477 as well as the issue template that you have used.
