### ISSUE TITLE
furo 2024.7.18 not compatible with sphinx>= 8.0

### ISSUE THREAD

**Issue by JohnVillalovos** [pradyunsg/furo#825]
sphinx 8.0 was released on 29-Jul-2024.

When attempting to install get the error message:

```
The conflict is caused by:
    The user requested sphinx==8.0.2
    furo 2024.7.18 depends on sphinx<8.0 and >=6.0
```

**Comment by Eric-Arellano** [comment]
Fixed in https://github.com/pradyunsg/furo/commit/2d3b6baa3371451d997d879a0aa61b3592ade638 and tracked by https://github.com/pradyunsg/furo/discussions/824. (Pradyun requests that discussions are used for requests, rather than issues, per https://github.com/pradyunsg/furo/issues/477)
