### ISSUE TITLE
Sphinx gallery formatting

### ISSUE THREAD

**Issue by adamgayoso** [pradyunsg/furo#83]
**Describe the bug**
The thumbnail and title of nbsphinx gallery elements are misaligned. It seems to be specific to furo.

**To Reproduce**
https://nbsphinx.readthedocs.io/en/furo-theme/subdir/gallery.html

This uses the sphinx gallery css as far as I understand.

**Expected behavior**
https://nbsphinx.readthedocs.io/en/latest/subdir/gallery.html

**Comment by pradyunsg** [comment]
<img width="256" alt="Screenshot 2021-02-27 at 11 49 34 AM" src="https://user-images.githubusercontent.com/3275593/109386330-e20ebc00-78f1-11eb-8e8a-d98e8c91083e.png">

Seems to be because nbsphinx-gallery is writing styles that aren't compatible with Furo's approach to centering items.

**Comment by pradyunsg** [comment]
Should be resolved by 9ef867b963a953073d6e1ea20612350d1223f078. :)
