### ISSUE TITLE
Support for ABlog

### ISSUE THREAD

**Issue by damian-krawczyk** [pradyunsg/furo#86]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
I would like furo theme to support [ABlog](https://ablog.readthedocs.io). It would be good to support even the simplest form: 
 - properly formated list of posts on single page
 - properly formated single article

**Describe alternatives you've considered**
n/a

**Additional context**
See examples of ABlog for Sphinx in use:

- https://www.ericholscher.com
- https://predictablynoisy.com/blog/

**Comment by pradyunsg** [comment]
Thanks for filing this issue!

You'll need to be more specific about what supporting ABlog would mean/need. What works right now, and what doesn't; why Furo needs to be the one that adds compatibility (rather than the other way round etc).

**Comment by pradyunsg** [comment]
Closing due to the lack of a response. Feel free to poke this again.

**Comment by damian-krawczyk** [comment]
@pradyunsg [here](https://github.com/sunpy/ablog/issues/108) I put more details with examples you can check how it works with default theme `alabaster`, `pydata_sphinx_theme` and error for `furo` theme.

**Comment by sudopluto** [comment]
https://github.com/pradyunsg/furo/blob/121edb3e9ade5e7cfc8c75d64190b66d0e7ddb08/docs/changelog.md#20210320beta31

is this relevant?

**Comment by sudopluto** [comment]
looks like (only?) two files to change: https://github.com/sunpy/ablog/search?q=layout.html

**Comment by errbufferoverfl** [comment]
@damian-krawczyk I recently made some changes to the [furo theme to support ablog](https://github.com/errbufferoverfl/furo), as it currently stands it should work as both a normal Sphinx theme, and an ablog theme and did my best to ensure no breaking changes.

If you plan on testing it locally you'll need to follow the instructions on the [workflow](https://pradyunsg.me/furo/contributing/workflow/) to get it to get all the Sass stylesheets and Javascript code working.

Good luck!
