### ISSUE TITLE
Short main content with a large toctree causes additional whitespace in main content

### ISSUE THREAD

**Issue by jackbentley** [pradyunsg/furo#87]
**Describe the bug**
When the main content is shorter than the total height (not considering the scroll bar) of the toctree, additional whitespace is added to the bottom of the main content.

**To Reproduce**

1. Create a short page - a sentence or two
2. Ensure there is a lot of content in the toctree
3. Scroll down

**Expected behavior**
You shouldn't be able to scroll a page that has no content that goes into the scrolled space.

**Screenshots**
![scroll2](https://user-images.githubusercontent.com/9383439/109190825-6c89db00-778d-11eb-8d00-c2517f6fc988.gif)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 87.0.4280.141

**Potential solution**
It seems to be caused by this line. Removing it or forcing `100vh` seems to fix it - however, I'm unsure what this line does.
https://github.com/pradyunsg/furo/blob/main/src/furo/assets/styles/_scaffold.sass#L95

**Comment by pradyunsg** [comment]
Oh fun. It's there for looking OK on mobile displays, but I think I messed up desktop displays in the process. :)

**Comment by pradyunsg** [comment]
Fixed in beta26! :)
