### ISSUE TITLE
furo.css Path Broken in 2021.02.28.beta27

### ISSUE THREAD

**Issue by t-mart** [pradyunsg/furo#90]
[My RTD site](https://wow-addon-packager.readthedocs.io/en/stable/) is using `2021.02.28.beta27` that was just released.

In the past few hours, I noticed that the CSS was broken. Looking more into it with my browser's development tools, I noticed  an error in the console:

```
(index):1 Refused to apply style from 'https://wow-addon-packager.readthedocs.io/en/stable/_static/styles/furo.css%3Fdigest%3Dbe5985a4059b5c2cd56ed0804790452beca62674.html' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled
```

The HTML is requesting:

``` html
<link rel="stylesheet" href="_static/styles/furo.css%3Fdigest%3Dbe5985a4059b5c2cd56ed0804790452beca62674.html">
```

I think this URL is broken. Looking back on another build that uses `2021.02.28.beta26` (the prior version), that link is expressed as:

``` html
<link rel="stylesheet" href="_static/styles/furo.css?digest=8304b39bb3b7aeb8294a71b3712567f018b3dac4">
```

The difference *perhaps* being that the query parameter symbols `?` and `=` are URL-encoded and there's an extra `.html` suffix in the broken version. The error seems to indicate that my browser thinks this file is HTML, not CSS as intended.

Sure enough, when I convert the link to use those symbols literally, the CSS request resolves normally:
- Broken: https://wow-addon-packager.readthedocs.io/en/stable/_static/styles/furo.css%3Fdigest%3Dbe5985a4059b5c2cd56ed0804790452beca62674.html
- Fixed: https://wow-addon-packager.readthedocs.io/en/stable/_static/styles/furo.css?digest?Dbe5985a4059b5c2cd56ed0804790452beca62674.html

Something has changed recently with how this URL is generated.

**Comment by pradyunsg** [comment]
Ooooops! Yanked beta27 and uploaded beta28 as well. Lemme know if beta28 doesn't fix this. :)

**Comment by t-mart** [comment]
Thanks @pradyunsg! I'm back in business.

Other RTD users should rebuild their affected versions. (You may also have to hard refresh (Shift-F5) and/or wipe your version from the RTD console. Not sure which one fixed it.)

**Comment by pradyunsg** [comment]
Well, it should only affect folks who built things in the 3 hours between the releases and yank.
