### ISSUE TITLE
Field report: An attempt to adopt furo

### ISSUE THREAD

**Issue by enkore** [pradyunsg/furo#98]
I've recently tried to replace sphinx_rtd_theme with furo in a project. In the end we (team of ten) chose not to, but the observations and problems we found might provide some valuable feedback. I am aware that some (perhaps all) of these have been discussed previously here, and in some cases are considered wontfix. I'll be conveying those points anyway.

I'd describe the size of the docs for that project as "medium-sized", if you'd print it out, it'd be around 70-80 A4 pages. I think the overall structure is fairly typical with three or so top-level chapters with up to half a dozen pages consisting of 2-15 headings.

- People found it confusing/surprising that the page adapts to light/dark mode, without a dark mode switch or a hint that it does this. It seems like "browser UI set to dark mode" -> "user wants all pages in dark mode" is not a safe conclusion. Discussed in: #24 
- Disabling dark mode (or light mode) is wontfix: #28   The concern here is mostly that it's super-hard to make diagrams that would work well in both modes, and also branding is way harder to do with effectively two completely different themes.

  The goal is definitely laudable, but there is a range of projects which have more than just text—where dark mode is easy for the project, thanks to the great work you did in furo—but aren't large enough to feasibly support two variants of all images/diagrams. For those projects a toogle to just disable one of them seems reasonable.
- Regarding the split table of contents:
  - Some liked it, while some found it confusing that there are two, but this generally didn't seem like a big hangup
  - n>=1 disliked the bad navigation, with no way to jump to a heading on page. This was due to the browser window being sized such that the right ToC was replaced with a small button, which made it effectively invisible, despite there still being some screen space left.
  
      This happens when a browser window takes up 50 % of the width of a 1920x1080 screen, and still happens on a 2560x1440 screen at 50 % width. The former situation is probably okay, in the latter case there is quite a lot of whitespace.
- The "per page ToC" shows up as soon as there are any inner headings. This is a somewhat awkward situation with most Sphinx themes.
- The title of the "per page ToC" is not easily changed, because it is hardcoded in page.html. People found "Contents:" unclear, especially as our top-level toctree used the exact same wording, so effectively both ToCs were titled "Contents:". I ended up changing the main ToC to "Table of Contents", and overwrote page.html changing the text to "Page Contents".
- Pure black on pure white (and vice versa) was found jarring by some.
- A very good thing about Furo: No dependencies, no bloat in the output (like webfonts, additional JS libraries etc.), which resulted in a leaner docs package and much better loading times compared to sphinx_rtd_theme.

Overall Furo is really good and was received very well. I could see Furo becoming quite popular, since there really aren't many modern and good-looking Sphinx themes (most look quite dated unfortunately), Furo really sets itself apart from these.

(eref 42d478fb6976)

**Comment by johnthagen** [comment]
> The concern here is mostly that it's super-hard to make diagrams that would work well in both modes

I'd like to echo this. We build diagrams with a transparent background so that they look really nice in the page. Without being able to force a light or dark theme, these diagrams look really bad in one or another. It is a lot of work to maintain two sets of everything. We were hoping to use `furo` as a really clean dark theme, but we really need the ability to force dark. (#100, #24, #28)

**Comment by pradyunsg** [comment]
Thanks @enkore for this! This is great context and perspective to have, and the feedback is genuinely appreciated! ^>^

Looks like the "sticking points" were the way the responsive breakpoints for the theme work and dark-mode/light-mode handling. I've been experimenting with the responsive breakpoints for a few days now, and I think I have an idea that'll work pretty well. Now, it's a matter of me having enough free time to fiddle with the SCSS for getting that working! :)

The color stuff already has existing issues/discussions, so I won't go into that here.

**Comment by pradyunsg** [comment]
> Pure black on pure white (and vice versa) was found jarring by some.

Oh, and this is why everything is exposed as CSS variables -- https://pradyunsg.me/furo/customisation/colors/#defining-overrides-for-defaults

You can set `color-background` and `color-foreground`, to tweak them if you want! :)
