### ISSUE TITLE
Google docstring style

### ISSUE THREAD

**Issue by AgentDS** [pradyunsg/furo#99]
Hi,

 really like your sphinx theme. It seems your demo for API docstring are in raw rst style. Do you support other API docstring style like Numpy and Google style? For exmaple:
```python
    def MyFunc(block, layers, num_classes=10):
        """Return a random page.

        Performs a GET request to the /page/random/summary endpoint.

        Args:
            block: net block.
            layers (list): number of blocks for each layer
            num_classes (int): number of classifier's output classes

        Returns:
            int
        """
```

In other words, is your theme compatible with extension `sphinxcontrib.napoleon`?

**Comment by stonecharioteer** [comment]
It should be, I'm using napoleon and Furo at work. Can't post screenshots
though.

**Comment by pradyunsg** [comment]
I'm pretty sure that'll work, because they generate the same HTML as far as I can tell.

**Comment by AgentDS** [comment]
> I'm pretty sure that'll work, because they generate the same HTML as far as I can tell.

Oh it works! but I still have problem.
Here is my source code:
```python
# ResNet
class ResNet(nn.Module):
    """Return a random page.

    Performs a GET request to the /page/random/summary endpoint.

    Args:
        block: net block.
        layers (list): number of blocks for each layer
        num_classes (int): number of classifier's output classes

    Returns:

    Raises:
        ClickException: The HTTP request failed or the HTTP response
            contained an invalid body.

    Example:
        >>> from docsexp.models import ResNet, ResidualBlock
        >>> model = ResNet(ResidualBlock, [2, 2, 2])
    """
    def __init__(self, block, layers, num_classes=10):
        super(ResNet, self).__init__()
        self.in_channels = 16
        self.conv = conv3x3(3, 16)
        self.bn = nn.BatchNorm2d(16)
        self.relu = nn.ReLU(inplace=True)
        self.layer1 = self.make_layer(block, 16, layers[0])
        self.layer2 = self.make_layer(block, 32, layers[1], 2)
        self.layer3 = self.make_layer(block, 64, layers[2], 2)
        self.avg_pool = nn.AvgPool2d(8)
        self.fc = nn.Linear(64, num_classes)

    def make_layer(self, block, out_channels, blocks, stride=1):
        downsample = None
        if (stride != 1) or (self.in_channels != out_channels):
            downsample = nn.Sequential(
                conv3x3(self.in_channels, out_channels, stride=stride),
                nn.BatchNorm2d(out_channels))
        layers = []
        layers.append(block(self.in_channels, out_channels, stride, downsample))
        self.in_channels = out_channels
        for i in range(1, blocks):
            layers.append(block(out_channels, out_channels))
        return nn.Sequential(*layers)


    def forward(self, x):
        out = self.conv(x)
        out = self.bn(out)
        out = self.relu(out)
        out = self.layer1(out)
        out = self.layer2(out)
        out = self.layer3(out)
        out = self.avg_pool(out)
        out = out.view(out.size(0), -1)
        out = self.fc(out)
        return out
```

use command to build:
```bash
# under the project folder
sphinx-apidoc -f -o docs/source docsexp; cd docs; make html
```

I got this:
<img width="857" alt="Screen Shot 2021-03-13 at 5 18 30 PM" src="https://user-images.githubusercontent.com/19991349/111025609-25077e00-8420-11eb-80b4-949c66521a92.png">
why the __init__ args are not shown in the class name `ResNet`? instead there are unknown args like `*args: Any, **kwargs: Any`

**Comment by pradyunsg** [comment]
🤷🏻‍♂️

That's not related to the theme though.

I'll suggest asking this in some other Sphinx-related support channels (https://groups.google.com/g/sphinx-users for example) or on the extension's community channels, since they're better placed to help you with those issues. :)

I'll go ahead and eagerly close this, since there's nothing actionable on this theme's end here. ^.^

**Comment by AgentDS** [comment]
> Idk. I don't know much about that extension. 🤷🏻‍♂️
> 
> The issue is not related to the theme though.
> 
> I'll suggest asking this in some other Sphinx-related support channels (https://groups.google.com/g/sphinx-users for example) or on the extension's community channels, since they're better placed to help you with those issues. :)
> 
> I'll go ahead and eagerly close this, since there's nothing actionable on this theme's end here. ^.^

thank you!
